### ISSUE TITLE
auto_offset_reset=-1 not respected for new consumer groups

### ISSUE THREAD

**Issue by ottomata** [Parsely/pykafka#241] opened 2015-08-31 20:16 UTC
I noticed that new consumer groups don't start consuming from the end of a topic even if ```auto_offset_reset=-1``` (the default), unless I also set ```reset_offset_on_start=True```.  However, if I set ```reset_offset_on_start=True```, existent consumer groups will always consume from the end of the topic, even if they have committed offsets.

I tested 4 different combinations of consumer groups and ```reset_offset_on_start```.  For all cases below, ```auto_offset_reset=-1``` (the default).  Here's what I found:

- New consumer group, ```reset_offset_on_start=False```: starts consuming at earliest offset.
- New consumer group, ```reset_offset_on_start=True```: starts consuming at latest offset.
- Existent consumer group, ```reset_offset_on_start=False```: starts consuming at committed offset.
- Existent consumer group, ```reset_offset_on_start=True```: starts consuming at latest offset.

I'm running Kafka 0.8.2.1 and pykafka 2.0.0.

This is a pretty annoying bug, as it means there is no simple way to have a consumer that starts consuming from latest offset UNLESS there is a committed offset, which I believe is the intended behavior of ```auto_offset_reset=-1```.

What should happen with ```auto_offset_reset=-1``` and  ```reset_offset_on_start=False```:

- New consumer group, ```reset_offset_on_start=False```: starts consuming at **latest** offset.
- Existent consumer group, ```reset_offset_on_start=False```: starts consuming at committed offset.

Thanks!

**Comment by rduplain** [comment] 2015-08-31 22:59
Thanks for posting this! In addition to clearing up the issue here, pykafka would benefit from more doc coverage on how to start consuming. This issue is worth converting into a doc.

**Comment by rduplain** [comment] 2015-09-01 15:37
Yes, the issue needs fixed, then the issue text should be converted into a doc. (Sorry if I was unclear.)

**Comment by ottomata** [comment] 2015-09-01 19:39
Ok, I've been poking at this all day, and I think the issue comes from that fact that Kafka will return -1 for an offset request for a consumer group that doesn't have a committed offset **and** that returned -1  is being passed to ```owned_partitions.set_offset()``` at https://github.com/Parsely/pykafka/blob/master/pykafka/simpleconsumer.py#L385 and then subsequently being incremented to 0 by ```set_offset()``` at https://github.com/Parsely/pykafka/blob/master/pykafka/simpleconsumer.py#L659.

I tried to figure out what the proper thing to do was, but my changes keep fixing one thing and breaking another.  I was trying to somehow special case a negative offset in the ```_handle_success()``` methods, but since the meaning of '-1' is being overloaded here, it gets complicated.  In one case, -1 means "start from the latest offset", but when returned from an offset request, Kafka intends it to mean "there is no offset yet committed".

Perhaps each ```OwnedPartition``` needs to know the value of ```auto_offset_reset``` so that it can special case a -1 in ```set_offset```, with both ```self.last_offset_consumed``` and ```self.next_offset``` initialized to the value of ```auto_offset_reset```.

**Comment by ottomata** [comment] 2015-09-02 02:34
Does that work? :)

**Comment by emmett9001** [comment] 2015-09-02 18:59
@ottomata Thanks for checking this in. I don't entirely follow your original post. You mention

    no simple way to have a consumer that starts consuming from latest offset

but you also list this as one of the four possible behaviors:

    New consumer group, reset_offset_on_start=True: starts consuming at latest offset.

It sounds to me like this is what you're looking for? If you want a new consumer to start consuming from the latest available offset, why not use `reset_offset_on_start=True`?

**Comment by ottomata** [comment] 2015-09-02 19:14
The problem I am having is with new consumer groups and ```auto_offset_reset=-1```.  In this case, there are no offsets stored, but according to https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-OffsetFetchRequest, this is not an error.

> Note that if there is no offset associated with a topic-partition under that consumer group the broker does not set an error code (since it is not really an error), but returns empty metadata and sets the offset field to -1.

This makes ```_handle_success``` for ```fetch_offsets``` be called, which then calls ```owned_partition.set_offset(pres.offset)```.  In this case, Kafka has returned -1, so ```pres.offset``` is -1.  That is then passed to ``set_offset```, and subsequently incremented to 0 by:

```
self.next_offset = last_offset_consumed + 1
```
On L663 of simpleconsumer.py.

The consumer then proceeds to make a fetch_request at offset 0, which causes the consumer to start consuming from the beginning of the stream.

Hm, perhaps this is only happening to me because offset 0 still exists in my topic.  Is this just an edgecase where offset 0 is a valid offset?  That might make sense, because if 0 was not a valid offset for my topic, then the fetch request would get an error, which I suppose should cause ```reset_offsets``` to be called with the value of ```auto_offset_reset```, which should then do the right thing?

> It sounds to me like this is what you're looking for? If you want a new consumer to start consuming from the latest available offset, why not use reset_offset_on_start=True?

Maybe, but wouldn't this cause offsets to be reset for consumer groups that exist?  I don't want to have to pass different parameters to my consumer depending on if the consumer group already exists or not.

**Comment by ottomata** [comment] 2015-09-02 19:29
Y'all on IRC?  I'm ottomata on freenode if you want to chat.

**Comment by emmett9001** [comment] 2015-09-02 19:30
I'm trying to distill this issue to its base. You'd like some mode of operation in which any "new" consumer group (no committed offsets) starts from the latest *available* offset, and any "existing" consumer group (with >= 1 committed offset) starts from its latest *committed* offset. That is, some single combination of settings that behaves in this way. Is this an accurate assessment?

Assuming it is, and thinking about the existing options: `reset_offset_on_start` being `True` makes a new consumer group start at the latest available offset, and an existing consumer do the same - not what you're looking for. This option being `False` makes a new consumer group start at offset `0` as you've described, and makes an existing group start from its latest committed offset - also not what you're looking for.

**Comment by ottomata** [comment] 2015-09-02 19:37
>You'd like some mode of operation in which any "new" consumer group (no committed offsets) starts from the latest available offset, and any "existing" consumer group (with >= 1 committed offset) starts from its latest committed offset. That is, some single combination of settings that behaves in this way. Is this an accurate assessment?

Naw.  I want:

A. New consumer group, ```auto_offset_reset=-1```: starts consuming at latest offset.
B. New consumer group, ```auto_offset_reset=-2```: starts consuming at earliest offset
C. Existent consumer group, ```auto_offset_reset=-1```: starts consuming at committed offset.
D. Existent consumer group, ```auto_offset_reset=-2```: starts consuming at committed offset.

Currently, A does not happen. In case A, my consumer starts consuming from the earliest offset.

**Comment by ottomata** [comment] 2015-09-02 19:40
Oh, I'm sorry, I read your statement wrong.  I didn't see the 'its latest committed offset' part, and just read latest offset.  Yes, your statement is what I'm looking for, and seems to me to be the intended behavior of ```auto_offset_reset=-1```.

**Comment by emmett9001** [comment] 2015-09-02 19:49
Ok, thanks for helping me figure that out. Knowing that, I personally see this as more of a feature request than a bug, since the way it currently works is exactly as intended. I'm not totally sure I can see the use case for this, but you appear to have one! It would be great to find a way to support both the current behavior and this new one elegantly.

**Closed** 2015-09-02 22:15 UTC
Labels: enhancement, hazy
