### ISSUE TITLE
Message not delivering

### ISSUE THREAD

**Issue by kadnan** [Parsely/pykafka#812] opened 2018-06-05 03:11 UTC
I am writing this simple program by following the example and it gives an error:

```
Failed to connect newly created broker for b'adnans-mbp':9092
Error encountered when producing to broker b'adnans-mbp':9092. Retrying.
Error encountered when producing to broker b'adnans-mbp':9092. Retrying.
Error encountered when producing to broker b'adnans-mbp':9092. Retrying.
Error encountered when producing to broker b'adnans-mbp':9092. Retrying.
Message not delivered!! SocketDisconnectedError()
```

The program is given below:
```
from pykafka import KafkaClient

if __name__ == '__main__':
   client = KafkaClient("0.0.0.0:9092", broker_version='0.10.0')
    # client = KafkaClient("0.0.0.0:9092")
    topic = client.topics[b'poem']
    producer = topic.get_producer()
    producer.produce(b"your message")

    consumer = topic.get_simple_consumer()
    msg = consumer.consume()
    print(' % s[key = % s, id = % s, offset = % s]' %
          (msg.value, msg.partition_key, msg.partition_id, msg.offset))
```

I enabled logging and here is the dump:
```
INFO:pykafka.cluster:Requesting API version information
INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
INFO:pykafka.cluster:Got api version info: {0: ApiVersionsSpec(key=0, min=0, max=5), 1: ApiVersionsSpec(key=1, min=0, max=7), 2: ApiVersionsSpec(key=2, min=0, max=2), 3: ApiVersionsSpec(key=3, min=0, max=5), 4: ApiVersionsSpec(key=4, min=0, max=1), 5: ApiVersionsSpec(key=5, min=0, max=0), 6: ApiVersionsSpec(key=6, min=0, max=4), 7: ApiVersionsSpec(key=7, min=0, max=1), 8: ApiVersionsSpec(key=8, min=0, max=3), 9: ApiVersionsSpec(key=9, min=0, max=3), 10: ApiVersionsSpec(key=10, min=0, max=1), 11: ApiVersionsSpec(key=11, min=0, max=2), 12: ApiVersionsSpec(key=12, min=0, max=1), 13: ApiVersionsSpec(key=13, min=0, max=1), 14: ApiVersionsSpec(key=14, min=0, max=1), 15: ApiVersionsSpec(key=15, min=0, max=1), 16: ApiVersionsSpec(key=16, min=0, max=1), 17: ApiVersionsSpec(key=17, min=0, max=1), 18: ApiVersionsSpec(key=18, min=0, max=1), 19: ApiVersionsSpec(key=19, min=0, max=2), 20: ApiVersionsSpec(key=20, min=0, max=1), 21: ApiVersionsSpec(key=21, min=0, max=0), 22: ApiVersionsSpec(key=22, min=0, max=0), 23: ApiVersionsSpec(key=23, min=0, max=0), 24: ApiVersionsSpec(key=24, min=0, max=0), 25: ApiVersionsSpec(key=25, min=0, max=0), 26: ApiVersionsSpec(key=26, min=0, max=0), 27: ApiVersionsSpec(key=27, min=0, max=0), 28: ApiVersionsSpec(key=28, min=0, max=0), 29: ApiVersionsSpec(key=29, min=0, max=0), 30: ApiVersionsSpec(key=30, min=0, max=0), 31: ApiVersionsSpec(key=31, min=0, max=0), 32: ApiVersionsSpec(key=32, min=0, max=1), 33: ApiVersionsSpec(key=33, min=0, max=0), 34: ApiVersionsSpec(key=34, min=0, max=0), 35: ApiVersionsSpec(key=35, min=0, max=0), 36: ApiVersionsSpec(key=36, min=0, max=0), 37: ApiVersionsSpec(key=37, min=0, max=0), 38: ApiVersionsSpec(key=38, min=0, max=0), 39: ApiVersionsSpec(key=39, min=0, max=0), 40: ApiVersionsSpec(key=40, min=0, max=0), 41: ApiVersionsSpec(key=41, min=0, max=0), 42: ApiVersionsSpec(key=42, min=0, max=0)}
INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
INFO:pykafka.cluster:Discovered 1 brokers
INFO:pykafka.connection:Failed to connect to b'adnans-mbp':9092
INFO:pykafka.connection:[Errno 8] nodename nor servname provided, or not known
WARNING:pykafka.broker:Failed to connect newly created broker for b'adnans-mbp':9092
INFO:pykafka.cluster:Discovered 2 topics
INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
INFO:pykafka.topic:Adding 1 partitions
INFO:pykafka.simpleconsumer:Starting 1 fetcher threads
INFO:pykafka.simpleconsumer:Updating cluster in response to error in fetch() for broker id 0
INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
INFO:pykafka.cluster:Discovered 1 brokers
INFO:pykafka.cluster:Reconnecting to broker id 0: b'adnans-mbp':9092
INFO:pykafka.connection:Failed to connect to b'adnans-mbp':9092
INFO:pykafka.connection:[Errno 8] nodename nor servname provided, or not known
INFO:pykafka.cluster:Failed to re-establish connection with broker id 0: b'adnans-mbp':9092
INFO:pykafka.cluster:Discovered 2 topics
INFO:pykafka.topic:Adding 1 partitions
INFO:pykafka.simpleconsumer:Updating cluster in response to error in fetch() for broker id 0
INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
INFO:pykafka.cluster:Discovered 1 brokers
INFO:pykafka.cluster:Reconnecting to broker id 0: b'adnans-mbp':9092
INFO:pykafka.connection:Failed to connect to b'adnans-mbp':9092
INFO:pykafka.connection:[Errno 8] nodename nor servname provided, or not known
INFO:pykafka.cluster:Failed to re-establish connection with broker id 0: b'adnans-mbp':9092
INFO:pykafka.cluster:Discovered 2 topics
INFO:pykafka.topic:Adding 1 partitions
INFO:pykafka.simpleconsumer:Updating cluster in response to error in fetch() for broker id 0
INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
INFO:pykafka.cluster:Discovered 1 brokers
INFO:pykafka.cluster:Reconnecting to broker id 0: b'adnans-mbp':9092
INFO:pykafka.connection:Failed to connect to b'adnans-mbp':9092
INFO:pykafka.connection:[Errno 8] nodename nor servname provided, or not known
INFO:pykafka.cluster:Failed to re-establish connection with broker id 0: b'adnans-mbp':9092
INFO:pykafka.cluster:Discovered 2 topics
INFO:pykafka.topic:Adding 1 partitions
INFO:pykafka.simpleconsumer:Updating cluster in response to error in fetch() for broker id 0
INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
INFO:pykafka.cluster:Discovered 1 brokers
INFO:pykafka.cluster:Reconnecting to broker id 0: b'adnans-mbp':9092
INFO:pykafka.connection:Failed to connect to b'adnans-mbp':9092
INFO:pykafka.connection:[Errno 8] nodename nor servname provided, or not known
INFO:pykafka.cluster:Failed to re-establish connection with broker id 0: b'adnans-mbp':9092
INFO:pykafka.cluster:Discovered 2 topics
INFO:pykafka.topic:Adding 1 partitions
INFO:pykafka.simpleconsumer:Updating cluster in response to error in fetch() for broker id 0
INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
INFO:pykafka.cluster:Discovered 1 brokers
INFO:pykafka.cluster:Reconnecting to broker id 0: b'adnans-mbp':9092
INFO:pykafka.connection:Failed to connect to b'adnans-mbp':9092
INFO:pykafka.connection:[Errno 8] nodename nor servname provided, or not known
INFO:pykafka.cluster:Failed to re-establish connection with broker id 0: b'adnans-mbp':9092
INFO:pykafka.cluster:Discovered 2 topics
INFO:pykafka.topic:Adding 1 partitions
```

**Comment by emmett9001** [comment] 2018-06-05 18:27
The script you've provided is correct, and is verified by the automated tests. Ensure that the machine you're running the script on has access to the kafka cluster you're trying to connect to. Also, you might try explicitly providing the `hosts` kwarg in `KafkaClient.__init__` like so:
```python
client = KafkaClient(hosts="0.0.0.0:9092", broker_version='0.10.0')
```
though I think that's unlikely to change anything.

I'm going to close this issue because I'm confident that this is not a bug in pykafka. Please comment or reopen if you'd like additional help or think I'm in error in closing the issue.

**Closed by emmett9001** 2018-06-05 18:27 UTC

**Comment by kadnan** [comment] 2018-06-06 08:17
I had to explicitly set `advertised.listeners` to `localhost` and it worked then.
