### ISSUE TITLE
MessageTooLarge uncaught failure using rdkafka

### ISSUE THREAD

**Issue by waypointsoftware** [Parsely/pykafka#438] opened 2016-01-30 19:07 UTC
Note that I am using SNAPPY compression on the producer.

Has anyone attempted to send a 2mb+ message to kafka with rdkafka turned on? I noticed that it puts an exception in the delivery report queue that states that the message is too large, but doesnt throw an exception at all. It just skips sending that message

With rdkafka turned off it posts to kafka just fine, which makes me think that rdkafka is either not compressing the message OR its not using the "compressed size" of the message to compare to kafka's message.max.bytes setting. Which is currently at the default of 1000000.

So what i think may be happening is without rdfkafka the pykafka library is compressing the 2mb message below the default setting and not throwing an exception, while the rdkafka producer is NOT compressing the message prior to checking that value.

**Comment by emmett9001** [comment] 2016-02-01 17:41
Thanks for posting this, @waypointsoftware. I'll need to dig in a bit, but from your description this sounds like a real issue.

**Comment by yungchin** [comment] 2016-02-01 23:44
>
> Has anyone attempted to send a 2mb+ message to kafka with rdkafka turned
> on? I noticed that it puts an exception in the delivery report queue that
> states that the message is too large, but doesnt throw an exception at all.
> It just skips sending that message
>
> I should add that the fact that the exception only shows up in the
delivery report is expected behaviour. You can only get this exception
raised directly from `produce()` if you run the producer with `sync=True`.

But definitely agree this sounds like a bug: if the same message posts fine
with `pykafka.Producer`, clearly the broker is happy to accept it, and so
`RdKafkaProducer` should be able to get it out too.

**Comment by emmett9001** [comment] 2016-02-05 23:28
@waypointsoftware Can you paste the exception you get from the rdkafka producer? The pure python producer doesn't actually do any checks on message size prior to sending a message, so correspondingly I'd expect the exception you get to be the result of an error code directly from Kafka. If that's the case, we probably need to fix our compression logic. What seems more likely to me, though, is that rdkafka may be doing some size checks of its own. Either way it's hard to know without a traceback.

**Comment by emmett9001** [comment] 2016-02-05 23:46
[Here's](https://gist.github.com/emmett9001/6b010d163037ea681de5) some information from a test script I ran. One of the log outputs is from a run with `use_rdkafka=True`, the other is from a run where it's `False`. As you can see, when I generate 2MB of random data, both implementations refuse the message. What I'm wondering is whether you see the same result, and if so, whether there's a size to which you can set this dummy message at which rdkafka fails to send the message and pure python does not.

**Comment by waypointsoftware** [comment] 2016-02-06 02:52
The behavior I saw was that the non-rdkafka producer worked with the 2mb message and the rdkafka-producer just failed with the message in the delivery_reports about the MessageSizeTooLarge.  

We've since disable rdkafka and no longer see any issues. Though we arent sending messages that are very large, they are likely under 100k when compressed. That 1 message I had the issue with was abnormally large and thats why I even noticed it happening.

**Comment by jofusa** [comment] 2016-03-09 18:58
@waypointsoftware  This is likely related to this issue: https://github.com/Parsely/pykafka/pull/480

**Comment by emmett9001** [comment] 2016-03-22 20:38
I don't actually think this is related to #480, since the rdkafka code path doesn't share any logic with that fix. This seems more likely to be a bug in rdkafka-specific code.

**Comment by yungchin** [comment] 2016-05-04 10:37
I was revisiting this issue just now, with current master, and see the same behaviour as @emmett9001 reported: both the pure-python and rdkafka producers refuse the message. I even used a highly compressible payload: `2048 * 1024 * "_"`.

What's not obvious to me from the kafka docs is whether this is or isn't the expected behaviour: should message sizes be evaluated before or after compressing? In any case, pykafka and librdkafka seem to agree about refusing this payload.

**Comment by emmett9001** [comment] 2016-05-04 15:02
@yungchin If you also see both implementations agreeing, I suggest we close this.

**Closed by emmett9001** 2016-05-04 15:02 UTC
Labels: bug, librdkafka

**Comment by yungchin** [comment] 2016-05-07 08:11
Just happened onto this, which could explain things https://issues.apache.org/jira/browse/KAFKA-1718
