### ISSUE TITLE
Hang when attempting to discover offset manager

### ISSUE THREAD

**Issue by spudfkc** [Parsely/pykafka#420] opened 2016-01-18 22:24 UTC
PyKafka v2.1.2
Python 3.5

I have noticed that occasionally I will experience one of my tests hanging, specifically when the offset manager is trying to be discovered with a BalancedConsumer.

The topic is being created dynamically from my test case.

```
2016-01-18 22:11:02,093| shepherd.orgstreamer/77: Getting new Kafka consumer... @_get_kafka_consumer:112 #DEBUG
2016-01-18 22:11:02,097| pykafka.handlers/77: RequestHandler.stop: about to flush requests queue @stop:134 #INFO
2016-01-18 22:11:02,097| pykafka.topic/77: Adding 1 partitions @update:147 #INFO
2016-01-18 22:11:02,098| kazoo.client/77: Connecting to kafka:2181 @_connect:575 #INFO
2016-01-18 22:11:02,102| kazoo.client/77: Zookeeper connection established, state: CONNECTED @_session_callback:444 #INFO
2016-01-18 22:11:02,134| pykafka.balancedconsumer/77: Rebalancing consumer "74f0aa9b3750:bed7ddf6-d74b-4864-bd00-daf837cebece" for topic "b'vk.datarouter.data.filtered.shepherd.test.2'". @_rebalance:518 #INFO
2016-01-18 22:11:02,136| pykafka.balancedconsumer/77: Balancing 1 participants for 1 partitions.
Owning 1 partitions. @_decide_partitions:403 #INFO
2016-01-18 22:11:02,140| pykafka.cluster/77: Attempting to discover offset manager for consumer group 'b'shepherd.test.2'' @get_offset_manager:346 #INFO
```

And then it just hangs indefinitely. I have not yet tracked down the cause of this, but will investigate further and try to get a reproducible test case.

Update 01/20/2016: 
This is an annoying bug as it's preventing my automated tests from running reliably. It _seems_ to be only happening when attempting to consume (or maybe just creating the BalancedConsumer?) the first time with a new Kafka cluster.
It looks to be hanging at BalancedConsumer._rebalance() while it is waiting for the _rebalancing_lock.

**Comment by emmett9001** [comment] 2016-01-19 18:15
Thanks @spudfkc. I believe this is the same issue that we see in our own test cases. We haven't yet been able to pinpoint the cause, so do post any further information you find on it.

**Comment by emmett9001** [comment] 2016-01-25 23:37
@spudfkc These test hangs are really difficult because it's not always obvious how to replicate them reliably. Do you have a test case that hangs every time, or at least most of the time?

**Comment by cscheffler** [comment] 2016-04-14 07:56
**pykafka** 2.2.0, **python** 2.7.9, **kafka** 0.8.2.2

I observed the same behaviour in production last night. The trigger was that we shut down one Zookeeper node in a 3-node cluster and one Kafka broker in a 3-broker cluster for server maintenance.

All balanced consumers except one handled it gracefully. The one that didn't handle it well was left with the main process still running, but apparently not doing anything (no normal log output after the rebalance). The final log output before hanging was:

```
2016-04-13 23:31:15,280 - INFO - Adding 12 partitions
2016-04-13 23:31:15,281 - INFO - Updating leader for <pykafka.partition.Partition at 0x7f58d57527d0 (id=2)> from broker 1 to broker 2
2016-04-13 23:31:15,281 - INFO - Updating in sync replicas list for <pykafka.partition.Partition at 0x7f58d57527d0 (id=2)>
2016-04-13 23:31:15,281 - INFO - Updating leader for <pykafka.partition.Partition at 0x7f58d5752950 (id=8)> from broker 1 to broker 2
2016-04-13 23:31:15,281 - INFO - Updating in sync replicas list for <pykafka.partition.Partition at 0x7f58d5752950 (id=8)>
2016-04-13 23:31:15,281 - INFO - Updating leader for <pykafka.partition.Partition at 0x7f58d5752a50 (id=11)> from broker 3 to broker 2
2016-04-13 23:31:15,281 - INFO - Updating in sync replicas list for <pykafka.partition.Partition at 0x7f58d5752a50 (id=11)>
2016-04-13 23:31:15,281 - INFO - Attempting to discover offset manager for consumer group 'threaded_consumer_sessionizer_service'
2016-04-13 23:31:15,315 - INFO - Found coordinator broker with id 3
2016-04-13 23:31:16,255 - INFO - RequestHandler worker: exiting cleanly
```

Just in case it is useful, the full log output from when the rebalance starts until the process hangs is here: https://gist.github.com/cscheffler/01cd9da95425a5ef803d3be3f2338e1e

**Comment by emmett9001** [comment] 2016-05-13 18:12
This is hard to replicate reliably, but I can't close it because it's definitely a real issue. I'm keeping an eye out for new information we get from our production logs when stuff like this happens to us at Parsely (which it occasionally does).

**Comment by emmett9001** [comment] 2016-07-06 18:49
This has ceased to be a common occurrence in our automated testing, so I'm going to close it for now.

**Closed by emmett9001** 2016-07-06 18:49 UTC
Labels: bug, hazy
