### ISSUE TITLE
Rd Kafka Async Producer slow

### ISSUE THREAD

**Issue by kariya2** [Parsely/pykafka#665] opened 2017-03-16 23:18 UTC
Hey guys, I've been testing the async producer with and without rdkafka and it seems like the rdkafka version is slower. Any known reasons fro this?

**Comment by emmett9001** [comment] 2017-03-23 16:57
Closing this as a duplicate of #661. If you don't think that's accurate @kariya2, please comment.

**Closed by emmett9001** 2017-03-23 16:57 UTC
