### ISSUE TITLE
pykafka 2.0.1 silently stalling on disconnect from kafka broker

### ISSUE THREAD

**Issue by tigran-a** [Parsely/pykafka#319] opened 2015-10-28 12:29 UTC
Hi, 

As suggested by @yungchin here:  https://groups.google.com/forum/#!topic/pykafka-user/zmK5h7Mt2Wo reporting the following: 

Balanced consumer in  case of one kafka broker goes down will silently stuck in version of pykafka 2.0.1, while in version 1.1.1 it throws SocketDisconnectedError in some thread. 

Setup: 2 kafka brokers, two zookeeper nodes; one topic with two partitions; replication factor 2.
```
$ pip show pykafka
---
Name: pykafka
Version: 2.0.1
Location: /usr/local/lib/python2.7/dist-packages
Requires: kazoo, tabulate
```
Code snippet: http://pastebin.com/z0sssrvb
Sample output: 
```
...
735 | :Message1522.                                                                     
                        {0: 767, 1: 735}                                           
768 | :Message1523.                                                         
                        {0: 768, 1: 735}                            
No handlers could be found for logger "kazoo.recipe.watchers" 
```

[and silence]

Thanks

**Comment by emmett9001** [comment] 2015-10-28 17:06
Thanks, @tigran-a. I believe this is happening because the total number of brokers in the cluster has fallen below the replication factor for the topic your consumer is reading. When the number of brokers is greater than or equal to the replication factor, the consumer fails as expected with a `SocketDisconnectedError` instead of hanging. It's a bug that it hangs in this case, so I'll look into it.
If you'd like to help verify this theory, you can run the same test on a topic with replication factor 1 instead of 2.

**Comment by emmett9001** [comment] 2015-10-28 17:52
Here's a theory: say we have a three-node cluster running a topic with RF=2. When we lose one of those nodes, the cluster still contains enough nodes to fully satisfy the replication factor. Fetch requests can continue returning messages, which means [this return statement](https://github.com/Parsely/pykafka/blob/20db2ac88ac7a4f5710b41eebb8f3c8ab17827da/pykafka/simpleconsumer.py#L357) can be reached. On the subsequent call to `consume()`, [`_raise_worker_exceptions`](https://github.com/Parsely/pykafka/blob/20db2ac88ac7a4f5710b41eebb8f3c8ab17827da/pykafka/simpleconsumer.py#L345) is called and the `SocketDisconnectedError` is raised normally.

Now say that we have a two-node cluster running a topic with RF=2. In this case, when we lose a node, the cluster does not contain enough nodes to fully satisfy the replication factor. Fetch requests cannot return messages anymore (since Kafka's RF guarantee is no longer maintained), which means [this case](https://github.com/Parsely/pykafka/blob/20db2ac88ac7a4f5710b41eebb8f3c8ab17827da/pykafka/simpleconsumer.py#L358) will be hit repeatedly. Since the consumer is still `_running` and `block` and `consumer_timeout_ms` are set appropriately, the `while True` loop will spin indefinitely despite the `SocketDisconnectedError` encountered on the fetcher thread.

Assuming that logic is sound, [this pull request](https://github.com/Parsely/pykafka/pull/321) should fix it. Note that this simply fixes a bug in the existing exception-raising logic of the consumer - it doesn't yet make the consumer able to handle a broker going down without client code catching the exception.

**Comment by tigran-a** [comment] 2015-10-28 21:27
I've tried with 2 brokers,  a topic with 2 partitions and RF=1; it still stucks when one node goes down.
However I can't guarantee the credibility of this test... I changed kafka version (0.8.2.1 to 0.8.2.2) and had to use another producer (kafka-console-producer) because the previous one (bruce) stopped to work for some reasons.

**Comment by emmett9001** [comment] 2015-10-28 23:38
@tigran-a Take a look at this pull request and see if it fixes your issue: https://github.com/Parsely/pykafka/pull/322

**Comment by tigran-a** [comment] 2015-10-29 16:07
@emmett9001 with #322 and the described scenario.
I had two partitions whose leader was broker 1. If I shut down the broker 0, it continues the execution (just says something about no handlers.. ). Then I put broker 0 back, and shut down broker 1. Then it continuously on consumer.consume() was throwing an exception " Unable to connect to a broker to fetch metadata. See logs.". Then after some point the error becomes Errno 111 Connection refused.
It was all on two brokers, two partitions with replication 2. 

Tried to repeat the test, but then it went to Error 111 directly. Even though the broker was up again, the error was still there. I think "connection refused" should mean that it just tried to connect and it was refused, but in this case, it looks like it was an "old offense"

How should I tell my consumer to reconnect in this case?
I tried to guess with that code: http://pastebin.com/XZw4Mbwg  but it did not work. Connection refused. 
Some other try repeated the first result.

**Comment by emmett9001** [comment] 2015-10-29 16:59
@tigran-a The pykafka consumer and producer don't currently support maintaining their connections when the cluster has less nodes available than the replication factor dictates. This isn't trivial, since we need the user to be aware that they're not consuming or producing to all partitions. This may be something we'll be able to address in a future release, but I'm still going over the documentation to try and figure out exactly how/if such cases are supposed to be handled by clients.

**Comment by tigran-a** [comment] 2015-10-30 12:29
I may have very limited understanding of Kafka, but why one would like to have a partition with replication factor >1 ? As for me, that is just for the cases where a broker treating that partition went down, then the other that have a copy could take over. The fact that it can't ensure replication factor = 2 at that moment - i'd say it's just a warning, but it should not put down the whole system. It can be functional with only one copy of the partition before a new backup broker shows up. Maybe you could clarify a bit this point?

**Comment by tigran-a** [comment] 2015-10-30 12:32
Yes, I've just tried to have 3 brokers and a topic with RF =2 and the client continues working fine, if any moment of time one of three brokers is down.
Unfortunately we couldn't decrease the number of brokers, because to make the similar test, with RF = 1 and number of brokers 2, if the broker containing the partition goes suddenly down, it's impossible for kafka to take over to handle that partition, and it puts leader =-1 driving any consumer in an erroneous state

**Comment by emmett9001** [comment] 2015-10-30 18:52
If RF=1 with two brokers and one broker dies, some partitions will have no replica and thus will have no eligible leader broker. This is why Kafka returns -1 in this case, and why PyKafka currently does not support it. To run in such cases (when the number of available brokers is less than the replication factor), a client like PyKafka would have to make it clear that some messages were not being consumed due to lack of a leader for their partition.

**Comment by emmett9001** [comment] 2015-10-30 23:04
I've done some investigation and discovered that there is indeed a bug that makes the consumer unable to recover fully after the number of brokers crosses the threshold from less than the RF to greater than or equal to it. I'll be looking into this.

**Comment by tigran-a** [comment] 2015-11-02 08:27
Hi @emmett9001,  I understand the case with RF=1 and broker goes down (in this case there are problems).
However, from the consumer point of view, if RF=2 and there is only one broker up, this broker still has the full data for the partition, and the consumption can be performed successfully. What do I miss here?

**Comment by emmett9001** [comment] 2015-11-04 23:04
@tigran-a When RF=2 and there's only one broker available, I see kafka returning `-1` as the leader for some partitions. I'm not sure if this is a result of PyKafka doing something wrong or some configuration issue with kafka.

**Comment by emmett9001** [comment] 2015-11-04 23:20
This [pull request](https://github.com/Parsely/pykafka/pull/327) handles the `SocketDisconnectedError` in `commit_offsets`. This doesn't completely fix the issue, but it may improve the situation.

**Comment by tigran-a** [comment] 2015-11-05 08:20
@emmett9001 , I made a similar test, and yes, kafka returns -1 for some partitions:
```
# 3 brokers up (0,1,2)
$ bin/kafka-topics.sh --zookeeper ... --topic topyk --describe 
Topic:topyk     PartitionCount:2        ReplicationFactor:2     Configs:
        Topic: topyk    Partition: 0    Leader: 0       Replicas: 0,1   Isr: 0,1
        Topic: topyk    Partition: 1    Leader: 1       Replicas: 1,2   Isr: 1,2
# shutting down broker 1. Note: Replica set does not change, even if one went down
$ bin/kafka-topics.sh --zookeeper ... --topic topyk --describe 
Topic:topyk     PartitionCount:2        ReplicationFactor:2     Configs:
        Topic: topyk    Partition: 0    Leader: 0       Replicas: 0,1   Isr: 0
        Topic: topyk    Partition: 1    Leader: 2       Replicas: 1,2   Isr: 2
# shutting down broker 2. Partition 1 had leader 2, so became -1, as no other replica available
$ bin/kafka-topics.sh --zookeeper ... --topic topyk --describe 
Topic:topyk     PartitionCount:2        ReplicationFactor:2     Configs:
        Topic: topyk    Partition: 0    Leader: 0       Replicas: 0,1   Isr: 0
        Topic: topyk    Partition: 1    Leader: -1      Replicas: 1,2   Isr: 
```

Not clear for me why kafka does not recreate a replica on another available broker...
I also tried to do 
```
$ bin/kafka-topics.sh --zookeeper  ... --topic topyk  --replica-assignment 0:1,0:1 --alter
```
after shutting down only broker 2 (brokers 0 and 1 was running) and hoping that replicas would be reassigned. But nothing changed. Maybe because of that bug: https://issues.apache.org/jira/browse/KAFKA-1947 and we need to wait the next version.

**Comment by kbourgoin** [comment] 2015-11-06 17:53
@tigran-a based on the output above, it sounds like you may be running in issues with the [leader.imbalance.check.interval.seconds](http://kafka.apache.org/documentation.html) setting on the broker. (search the page for it, I can't link directly to the setting).

If I'm reading the above correctly, this is what you're expecting to happen:

1. All 3 brokers running, everything is great.
2. Turn off broker 1. Everything keeps running and the partitions which were previously on broker 1 are replicated between brokers 0 and 2. By the end, the RF=2 will be respected in that each broker has a full copy of the data.
3. Turn off broker 2. Since 0 has a full copy of the data, things keep running just fine.

This isn't strictly incorrect, but what you may be hitting is a matter of timing. The check for whether replicas are balanced only happens every 5 minutes. So if you waited 5 minutes between steps 2 and 3 there, you should see the expected behavior. If you turn off broker 2 too soon, then you're going to lose data that hasn't been fully replicated.

The key to noticing this is the In-Sync Replica (ISR) set. You can see in the output from step 2 that Kafka still wants partition 0 replicated to (0,1) but the ISR, the set of brokers that are in-sync, is only (0). This is because 1 is down and the partitions haven't rebalanced yet.

This may sound like a strange default, waiting 5min to replicate, but given the dataset of a loaded data node, it makes sense. Each partition of ours contains 10s of gigs of data, and there can be 50 to 100 partitions on a topic.  If we lost one of our brokers for a short time, say 30 seconds, we wouldn't want the cluster to start shuffling that much data, only to try to shuffle it back when it came back up.  This is, as I understand it, a pretty typical load for a Kafka node, so it makes sense that the defaults are tuned for that.

**Comment by tigran-a** [comment] 2015-11-06 19:13
@kbourgoin thanks for the explication, you understood me correctly, I'd expect these 3 steps. However I've just made a test, and basically step 2 is not completed in the sense that the replica is never moved to another broker. ISR stays the same. I checked the broker config (it's almost default) and there was no that option set, so I suppose it should be the default 300 seconds: 
```
$ bin/kafka-topics.sh --zookeeper ... --topic topyk --describe 
Topic:topyk     PartitionCount:2        ReplicationFactor:2     Configs:
        Topic: topyk    Partition: 0    Leader: 0       Replicas: 0,1   Isr: 0,1
        Topic: topyk    Partition: 1    Leader: 1       Replicas: 1,2   Isr: 2,1
$ # shutting down broker 1
$ bin/kafka-topics.sh --zookeeper ... --topic topyk --describe 
Topic:topyk     PartitionCount:2        ReplicationFactor:2     Configs:
        Topic: topyk    Partition: 0    Leader: 0       Replicas: 0,1   Isr: 0
        Topic: topyk    Partition: 1    Leader: 2       Replicas: 1,2   Isr: 2
$ date
Fri Nov  6 18:44:40 UTC 2015
$ date
Fri Nov  6 18:49:31 UTC 2015
$ bin/kafka-topics.sh --zookeeper ... --topic topyk --describe 
Topic:topyk     PartitionCount:2        ReplicationFactor:2     Configs:
        Topic: topyk    Partition: 0    Leader: 0       Replicas: 0,1   Isr: 0
        Topic: topyk    Partition: 1    Leader: 2       Replicas: 1,2   Isr: 2
$ date
Fri Nov  6 18:50:53 UTC 2015
$ bin/kafka-topics.sh --zookeeper ... --topic topyk --describe 
Topic:topyk     PartitionCount:2        ReplicationFactor:2     Configs:
        Topic: topyk    Partition: 0    Leader: 0       Replicas: 0,1   Isr: 0
        Topic: topyk    Partition: 1    Leader: 2       Replicas: 1,2   Isr: 2
$ date
Fri Nov  6 18:54:16 UTC 2015
$ bin/kafka-topics.sh --zookeeper ... --topic topyk --describe 
Topic:topyk     PartitionCount:2        ReplicationFactor:2     Configs:
        Topic: topyk    Partition: 0    Leader: 0       Replicas: 0,1   Isr: 0
        Topic: topyk    Partition: 1    Leader: 2       Replicas: 1,2   Isr: 2
$ date
Fri Nov  6 19:04:00 UTC 2015
$ bin/kafka-topics.sh --zookeeper ... --topic topyk --describe 
Topic:topyk     PartitionCount:2        ReplicationFactor:2     Configs:
        Topic: topyk    Partition: 0    Leader: 0       Replicas: 0,1   Isr: 0
        Topic: topyk    Partition: 1    Leader: 2       Replicas: 1,2   Isr: 2
```

That is, even after 19 minutes nothing changed, but I'd expect Replicas become 0,2 as well as ISR...

**Comment by kbourgoin** [comment] 2015-11-09 23:39
Hey @tigran-a, I'm working on this locally and I'm seeing exactly what you're seeing. However, with our production brokers, I see messages like this in `controller.log`:

```
[2015-11-09 23:30:13,462] TRACE [Controller 10]: checking need to trigger partition rebalance (kafka.controller.KafkaController)
[2015-11-09 23:30:13,463] DEBUG [Controller 10]: preferred replicas by broker (snipped because it's a list of all topics and partitions. it's huge.)
[2015-11-09 23:30:13,463] DEBUG [Controller 10]: topics not in preferred replica Map() (kafka.controller.KafkaController)
[2015-11-09 23:30:13,463] TRACE [Controller 10]: leader imbalance ratio for broker 10 is 0.000000 (kafka.controller.KafkaController)
[2015-11-09 23:30:13,464] DEBUG [Controller 10]: topics not in preferred replica Map() (kafka.controller.KafkaController)
[2015-11-09 23:30:13,464] TRACE [Controller 10]: leader imbalance ratio for broker 14 is 0.000000 (kafka.controller.KafkaController)
[2015-11-09 23:30:13,464] DEBUG [Controller 10]: topics not in preferred replica Map() (kafka.controller.KafkaController)
[2015-11-09 23:30:13,464] TRACE [Controller 10]: leader imbalance ratio for broker 13 is 0.000000 (kafka.controller.KafkaController)
[2015-11-09 23:30:13,464] DEBUG [Controller 10]: topics not in preferred replica Map() (kafka.controller.KafkaController)
[2015-11-09 23:30:13,464] TRACE [Controller 10]: leader imbalance ratio for broker 12 is 0.000000 (kafka.controller.KafkaController)
[2015-11-09 23:30:13,464] DEBUG [Controller 10]: topics not in preferred replica Map() (kafka.controller.KafkaController)
[2015-11-09 23:30:13,464] TRACE [Controller 10]: leader imbalance ratio for broker 11 is 0.000000 (kafka.controller.KafkaController)
```

That's running every 5 minutes for us. In the past, when we've had brokers go down, this is where the rebalancing activity has been logged.

I see a bunch of settings in our production machines not in the `server.properties` that ships with Kafka. I'll run through those and let you know which ones turn this on. It's a good sized list, so it'll take a bit for me to update (and it's the end of the day for me).

**Comment by tigran-a** [comment] 2015-11-10 05:45
Thanks, @kbourgoin . Out of curiosity, would it be possible to post somewhere your kafka settings used in production (in the ideal world with explanations of the values choice) ?

**Comment by kbourgoin** [comment] 2015-11-10 20:47
I looked more into this and I can't get it to balance replicas after a broker goes down. I asked on IRC and it turns out this process is wholly manual in Kafka.

What I had been seeing before, with `leader.imbalance.check.interval.seconds` was that it will balance which brokers are leaders for which partitions. That is, if a broker goes down and comes back up, eventually it'll be marked as leader for some partitions again, instead of having all the leadership concentrated on one broker.

Thanks for asking about this. I got to learn a little more about Kafka internals and it helped clear up something I was mistaken about. I'm going to close this ticket, now, though, since there's not a lot PyKafka can do about it. @emmett9001 has already fixed the problem where it silently hung.

**Closed** 2015-11-10 20:49 UTC
Labels: in progress, wontfix

**Comment by kbourgoin** [comment] 2015-11-10 20:52
@tigran-a didn't see your message there, sorry for the lack of response. I looked into the differing settings and they were all defaults we had specified in our production config, but aren't in the config packaged with Kafka. Nothing interesting to see there, unfortunately.
