### ISSUE TITLE
balancedconsumer fails to reown partitions in case of network failures

### ISSUE THREAD

**Issue by tigran-a** [Parsely/pykafka#565] opened 2016-06-09 11:37 UTC
Hello, 

We experience from time to time problems with balanced consumer: in case of network failures, some partitions left unconsumed. 
Here is an example, we are running two consumers in a group for a topic with 6 partitions. Normally each takes care of 3 partitions. In this gist: 
https://gist.github.com/tigran-a/c93ca879df25624120d09b15e5019952
you can see, that after connection issues, the consumer "lost" one partition. 
The other consumer "lost" 2 partitions.

If I stop both consumers and start them again, all partitions are used. 

Is there any reasonable workaround for that? 
E.g. periodically try to refresh/reown unowned partitions or so? 

**PyKafka version**:  2.4.0
**Kafka version**: 0.8.2.2

Thanks for any help!

**Comment by emmett9001** [comment] 2016-06-09 11:48
Thanks for filing this @tigran-a. We've seen it periodically at Parse.ly as well, and in those cases we simply restart the consumers. I'm not sure yet about an automated way to address this - suggestions are definitely welcome.

**Comment by tigran-a** [comment] 2016-06-09 11:54
Yes, but it happened close to 1 am, so... it affected the system till the morning where we could fix it. 

I had to mention, it happens independently of whether I use librdkafka backend or not. 

I think it is important issue. Do you have any ideas of the reason that provokes such behavior? Where the ownership of the partition is stored? 

Thanks!

**Comment by emmett9001** [comment] 2016-06-09 12:02
[This logic](https://github.com/Parsely/pykafka/blob/389e5ea725390be1d7e70474a676cb2ac088709e/pykafka/balancedconsumer.py#L330-L333) seems one likely source of this type of issue. It might pay to add some better retry logic around `NoNodeError`.

**Comment by tigran-a** [comment] 2016-06-09 12:20
But when the stop() is called? And why if I completely stop all the consumers, and start them again, the owned partition is released (in a first glance, if we have this kind of ghost-owner, then restarting consumers should not help) ?

**Comment by emmett9001** [comment] 2016-06-09 12:31
`stop()` might not be getting called in your case, though I do think it's still a likely source of this type of issue. [Here's](https://github.com/Parsely/pykafka/blob/389e5ea725390be1d7e70474a676cb2ac088709e/pykafka/balancedconsumer.py#L620) the other place where the `BalancedConsumer` gives up owned partitions. The network failure scenarios possible during this logic make it really complicated to reason about. What if multiple rebalances are triggered sequentially as a result of connection loss and the consumer is unable to connect to ZooKeeper to release its partitions?

**Comment by emmett9001** [comment] 2017-09-21 22:32
This could also be related to #701 (cc @tanaysoni), it may be worth reevaluating.

**Comment by tanaysoni** [comment] 2017-09-30 09:50
@tigran-a @emmett9001 I tried sporadically stopping Kafka brokers & Zookeeper on my local in order to simulate network failures, but I'm unable to reproduce this error on the master branch. The rebalance calls triggered are able to re-own all partitions among group's consumers, without leaving out any partition. With v2.4.0, I couldn't get rebalance itself to work.

@emmett9001 On a side note, I'm curious if going ahead we'd be focusing on Zookeeper based offsets. From what I have read, the Kafka based offsets scale better.

**Comment by emmett9001** [comment] 2017-10-01 01:31
@tanaysoni Thanks for the info, it sounds like it's reasonable to close this. You're correct that newer versions of Kafka allow Kafka-based offset storage and that it's preferable to using ZooKeeper under many circumstances, but we do still need to support ZK offsets for backward compatibility. In fact, we're still using Kafka 0.8.2 at @parsely, so fixes to this system are very useful to us.

**Closed by emmett9001** 2017-10-01 01:31 UTC
Labels: bug, hazy
