### ISSUE TITLE
simple consumer reset_offsets fails

### ISSUE THREAD

**Issue by yhuangbl** [Parsely/pykafka#733] opened 2017-10-11 19:31 UTC
I have a simple consumer and I want it to consume from an offset. However, even though there are new messages between the starting offset and current time (I manually checked from Kafka console and there are new messages), the consumer does not consume any message and is blocked indefinitely. 
Logger print out:
```
pykafka.simpleconsumer - WARNING - Offset reset for partition 0 to timestamp 34668160 failed. Setting partition 0's internal counter to 34668160
WARNING:pykafka.simpleconsumer:Offset reset for partition 1 to timestamp 34659355 failed. Setting partition 1's internal counter to 34659355
stop offset: {0: OffsetPartitionResponse(offset=[34668258], err=0), 1: OffsetPartitionResponse(offset=[34659479], err=0)}
```
abstract of the code:
```
consumer.reset_offsets(start_offsets)
for msg in consumer:
    if msg is not None:
            print msg.value
```

(with the same code, same version of python and pykafka, sometimes the consumer can print out messages, sometimes it doesn't)

**Comment by emmett9001** [comment] 2017-10-12 15:34
Potentially related to https://github.com/Parsely/pykafka/issues/728

**Comment by emmett9001** [comment] 2018-02-27 22:36
It seems clear to me that offset resetting to a specific offset/timestamp is broken. The only case in which I'm sure that offset resetting does work is when `-1` or `-2` is used to indicate the end/beginning of the partition. It's worth examining [this test](https://github.com/Parsely/pykafka/blob/a4b6793c655d10d6edfc705445ca11dd07692f70/tests/pykafka/test_simpleconsumer.py#L167) to add a case that reproduces the issues noted here and in #728

**Comment by chobeat** [comment] 2018-05-16 11:03
any news on this? I don't want to drop pykafka just because of this issue but I really need to read specific records.  Any known workaround?

**Comment by emmett9001** [comment] 2018-05-16 16:15
@chobeat Sorry for letting this one slip through the cracks. After https://github.com/Parsely/pykafka/issues/728#issuecomment-380973935 was solved, this issue seems straightforward to me. It looks from your posted log messages that you've supplied a timestamp to `reset_offsets` in seconds, not milliseconds. According to the [newly edited documentation](https://github.com/Parsely/pykafka/blob/340f8e16c8b0d9830b6fd889f3be7570015ba3eb/pykafka/topic.py#L151), this parameter needs to be in milliseconds. Give that documentation a read and see if it informs a fix for your issue.

**Comment by emmett9001** [comment] 2018-07-12 22:00
https://github.com/Parsely/pykafka/pull/834 changes the interface to `reset_offsets` such that it takes `datetime` instances as the `offsets_before` parameter in its `OffsetRequest`. Merging that change should be significant to close this issue.

**Comment by emmett9001** [comment] 2018-07-19 21:20
#834 is merged, and timestamp-based offset resetting works in master with `datetime` instances.

**Closed by emmett9001** 2018-07-19 21:20 UTC
Labels: question
