### ISSUE TITLE
balanced consumer jumped to very-old offsets after connectivity problems

### ISSUE THREAD

**Issue by tigran-a** [Parsely/pykafka#542] opened 2016-05-06 11:00 UTC
Hi, 

This issue caused some downtime for us today:  
https://gist.github.com/tigran-a/f4c8ca620f428fbd38785559fd41ef7d

Basically BalancedConsumer jumped to very old offsets 

I know these stories about "at least once" guarantee, but I don't think the things should happen like we had
(it started re-consumed from 2 days ago)

Any hints how to avoid this in the future? 

**PyKafka version**: 2.3.1
**Kafka version**: 0.8.2.2

Thanks!

**Comment by tigran-a** [comment] 2016-05-06 11:20
Additional info: as you can see, there were other balanced consumer running in parallel; the last one did not make this jump, so the partitions that it owned were not affected.

**Comment by emmett9001** [comment] 2016-05-06 17:47
Thanks @tigran-a. I agree that this isn't something that should happen - we actually see it occasionally in our production system as well.

**Comment by tigran-a** [comment] 2016-05-06 19:53
Thanks, Is there a way to avoid this kind of failures?

Will be there any difference, if we try to run it with librdkafka backend ? Or it's completely independent issue?

**Comment by emmett9001** [comment] 2016-05-06 20:44
I'd guess that there's a possibility this issue would go away using the rdkafka backend, but since I'm not sure of what's actually causing this issue at the moment, it's a bit hard to say for sure.

**Comment by tigran-a** [comment] 2016-05-06 20:53
The provided log with INFO loglevel is not enough to pinpoint the issue? 

I'm also wondering about his annying message: 
```
pykafka.cluster - ERROR - Socket disconnected during offset manager discovery. This can happen when using PyKafka with a Kafka version lower than 0.8.2.
```
because we're using kafka 0.8.2.2  

Is there an explanation to it?

Thanks!

**Comment by messense** [comment] 2016-05-08 08:21
Hi, I  also encountered this issue a few days ago with Kafka 0.9.1 and pykafka 2.3.1.

**Comment by emmett9001** [comment] 2016-07-27 17:18
@messense @tigran-a If you can replicate this issue with debug logging enabled, it might provide some helpful information we can use to discover the root cause. You can turn on debug logging by putting this at the top of your script that uses pykafka:
```python
    import logging
    kafkalogger = logging.getLogger('pykafka')
    kafkalogger.setLevel(logging.DEBUG)
    console_handler = logging.StreamHandler()
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    console_handler.setFormatter(formatter)
    console_handler.setLevel(logging.DEBUG)
    kafkalogger.addHandler(console_handler)
```

**Comment by emmett9001** [comment] 2016-08-05 21:53
In light of this message in the original log

    ERROR - Error committing offsets for topic 'redirects' from consumer id 'some.host.name:74830aa4-01ec-4c76-a0d2-12513b5a9c9c'(SocketDisconnectedError)

it seems like your consumer machine lost its connection to the offset manager, causing offset committing to fail. Given that, it makes sense that the consumer would resume from old offsets, especially if you have the offset commit interval set to a large value or if these failures had been ongoing.

**Comment by emmett9001** [comment] 2016-08-05 21:56
I'm going to close this issue given the lack of new and actionable information. If anyone on the thread has more information to share or ways to reliably replicate it, please comment here.

**Closed by emmett9001** 2016-08-05 21:56 UTC
Labels: bug, hazy
