### ISSUE TITLE
socket.gaierror: [Errno 11004] getaddrinfo failed

### ISSUE THREAD

**Issue by Emor93** [Parsely/pykafka#418] opened 2016-01-14 08:22 UTC
```
>>> from pykafka import KafkaClient
>>> client = KafkaClient(hosts='10.43.159.127:9092')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Python27\lib\site-packages\pykafka\client.py", line 73, in __init__
    source_address=self._source_address
  File "E:\Python27\lib\site-packages\pykafka\cluster.py", line 191, in __init__
    self.update()
  File "E:\Python27\lib\site-packages\pykafka\cluster.py", line 390, in update
    self._update_brokers(metadata.brokers)
  File "E:\Python27\lib\site-packages\pykafka\cluster.py", line 315, in _update_brokers
    source_port=self._source_port
  File "E:\Python27\lib\site-packages\pykafka\broker.py", line 140, in from_metadata
    source_port=source_port)
  File "E:\Python27\lib\site-packages\pykafka\broker.py", line 92, in __init__
    self.connect()
  File "E:\Python27\lib\site-packages\pykafka\broker.py", line 200, in connect
    self._connection.connect(self._socket_timeout_ms)
  File "E:\Python27\lib\site-packages\pykafka\connection.py", line 82, in connect
    (self.source_host, self.source_port)
  File "E:\Python27\lib\socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno 11004] getaddrinfo failed
```

**Comment by emmett9001** [comment] 2016-01-14 17:26
Hi @Emor93. Could this traceback be caused by some issue with your server or firewall configuration? When you run this code from the machine hosting your pykafka code, what's the output?
```python
import socket
socket.getaddrinfo('10.43.159.127', 9092)
```

**Comment by Emor93** [comment] 2016-01-15 02:16
Thank you!@emmett9001 
The output is [(2, 0, 0, '', ('10.43.159.127', 9092))]
>>> import socket
>>> socket.getaddrinfo('10.43.159.127', 9092)
[(2, 0, 0, '', ('10.43.159.127', 9092))]

When i shutdown the firewall configuration and run the 'client = KafkaClient(hosts='10.43.159.127:9092')' again,it's ouput is:
>>> from pykafka import KafkaClient
>>> client = KafkaClient(hosts='127.0.0.1:9092')
No handlers could be found for logger "pykafka.cluster"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pykafka\client.py", line 73, in __init__
    source_address=self._source_address
  File "pykafka\cluster.py", line 191, in __init__
    self.update()
  File "pykafka\cluster.py", line 379, in update
    metadata = self._get_metadata()
  File "pykafka\cluster.py", line 286, in _get_metadata
    'Unable to connect to a broker to fetch metadata. See logs.')
RuntimeError: Unable to connect to a broker to fetch metadata. See logs.

**Comment by emmett9001** [comment] 2016-01-15 20:08
Looks like [this line](https://github.com/Parsely/pykafka/blob/656f381823d1f6097eaad98ac2b5f66362ac5bfc/pykafka/cluster.py#L254) is failing for one reason or another. There's nothing in your example code that indicates that you're doing anything wrong, so I'm left to guess that it's some firewall configuration that's not allowing your pykafka machine to talk to kafka. For some more information, you could add this to your test script:
```python
import logging as log
log.basicConfig(level=log.DEBUG)
```
You can post the full output from that test run here, it may give us something more off of which to work.

**Comment by Emor93** [comment] 2016-01-16 05:59
@emmett9001 I had closed the firewall:
ip6tables      	0:off	1:off	2:off	3:off	4:off	5:off	6:off
iptables       	0:off	1:off	2:off	3:off	4:off	5:off	6:off

And the output is:
DEBUG:pykafka.connection:Connecting to 10.43.159.115:9092
DEBUG:pykafka.connection:Successfully connected to 10.43.159.115:9092
INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
INFO:pykafka.cluster:Discovered 1 brokers
DEBUG:pykafka.cluster:Discovered broker id 159115: centos115:9092
DEBUG:pykafka.connection:Connecting to centos115:9092
INFO:pykafka.handlers:RequestHandler worker: exiting cleanly
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    client = KafkaClient(hosts="10.43.159.115:9092")
  File "d:\pykafka-master\pykafka\client.py", line 73, in __init__
    source_address=self._source_address
  File "d:\pykafka-master\pykafka\cluster.py", line 191, in __init__
    self.update()
  File "d:\pykafka-master\pykafka\cluster.py", line 387, in update
    self._update_brokers(metadata.brokers)
  File "d:\pykafka-master\pykafka\cluster.py", line 314, in _update_brokers
    source_port=self._source_port
  File "d:\pykafka-master\pykafka\broker.py", line 140, in from_metadata
    source_port=source_port)
  File "d:\pykafka-master\pykafka\broker.py", line 92, in __init__
    self.connect()
  File "d:\pykafka-master\pykafka\broker.py", line 200, in connect
    self._connection.connect(self._socket_timeout_ms)
  File "d:\pykafka-master\pykafka\connection.py", line 82, in connect
    (self.source_host, self.source_port)
  File "E:\Python27\lib\socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno 11004] getaddrinfo failed

Thanks!

**Comment by tigran-a** [comment] 2016-01-17 08:51
Can it be the kafka broker configuration?
You connect by IP, but then if the metadata is fetched from the broker about all kafka brokers, and this can return some name that is, e.g. not resolvable, from the client (pykafka) host. 
Maybe it worth looking at hostname of the kafka host, and if it is resolvable from pykafka client host. 
Just in case, in `server.properties`, you also have `advertised.host.name=<hostname routable by clients>` parameter.  
Not sure though...

**Comment by emmett9001** [comment] 2016-01-19 19:16
@Emor93 I agree with @tigran-a that this is likely to be related to either the `advertised.host.name` or `host.name` property in your broker configuration. Check out your `server.properties`, and also try running this from your pykafka machine:
```python
import socket
socket.getaddrinfo('centos115', 9092)
```
If it fails, that strongly indicates that you need to change the advertised hostname of your broker to something that your pykafka machine can resolve.

**Comment by emmett9001** [comment] 2016-01-19 19:34
@Emor93 I'm going to close this issue. Please reopen if you find that these suggestions don't solve it for you. Thanks!

**Closed by emmett9001** 2016-01-19 19:34 UTC
Labels: question

**Comment by sunqb** [comment] 2016-07-04 11:14
i also have this problem , and when i add "host.name=127.0.0.1"  ,it ok!!!

**Comment by ahmishra** [comment] 2020-06-23 06:59
Same Here
