### ISSUE TITLE
A "pykafka.exceptions.UnknownMemberId" error occurred while consuming the message in the program

### ISSUE THREAD

**Issue by ltwin** [Parsely/pykafka#855] opened 2018-08-16 14:17 UTC
**PyKafka version**: 2.7.0
**Kafka version**: 1.1.0
**Log info**: 

> 2018-08-16 21:42:56	INFO	simpleconsumer.py: 301	Continuing in response to UnknownMemberId
2018-08-16 21:42:56	ERROR	simpleconsumer.py: 519	Error committing offsets for topic 'secondary' from consumer id 'pykafka-77974ba8-b5fc-4b8c-b1bf-538c079c38ae'(errors: {<class 'pykafka.exceptions.UnknownMemberId'>: [4, 5]})

**Comment by emmett9001** [comment] 2018-08-16 21:44
Duplicate of https://github.com/Parsely/pykafka/issues/517

**Closed by emmett9001** 2018-08-16 21:44 UTC
