### ISSUE TITLE
consumer fails with exception after

### ISSUE THREAD

**Issue by tigran-a** [Parsely/pykafka#330] opened 2015-11-05 13:58 UTC
a consumer was reading data, (1 msg per 4 sec) from a 3-nodes-kafka-cluster, topic of 2 partitions, RF 2, and suddenly (max 6 hours later) raised the exception:  
   raise KafkaException("Socket disconnected during offset manager "
KafkaException: Socket disconnected during offset manager discovery. This can happen when using PyKafka with a Kafka version lower than 0.8.2.

All three brokers are kafka 0.8.2.2

trying repeat...

**Comment by emmett9001** [comment] 2015-11-05 17:53
Possibly related to #314

**Comment by emmett9001** [comment] 2015-11-05 22:08
I'm marking this as a duplicate of #314 - we can revisit if it turns out to be different.

**Closed by emmett9001** 2015-11-05 22:08 UTC

**Comment by CogumelosMaravilha** [comment] 2017-01-12 12:26
Currently with pykafka==2.5.0 using Kafka 0.10.0.1 this error still happens.
ERROR:pykafka.cluster:Socket disconnected during offset manager discovery. This can happen when using PyKafka with a Kafka version lower than 0.8.2.

**Comment by emmett9001** [comment] 2017-01-12 21:59
@CogumelosMaravilha is this error causing a crash, or is it just printing as a log message? What code are you running that demonstrates this issue?

**Comment by CogumelosMaravilha** [comment] 2017-01-12 23:05
Just prints the message.

"""from __future__ import absolute_import, division, print_function, unicode_literals"""
import logging
import json
from cassandra.cluster import Cluster
from pykafka import KafkaClient

logging.basicConfig()
try:
    client = KafkaClient(hosts="kazoo001.olaeu.prv:9092, kazoo002.olaeu.prv:9092,"
                               "kazoo003.olaeu.prv:9092, kazoo004.olaeu.prv:9092,"
                               "kazoo005.olaeu.prv:9092")
except:
       print "############ Some problem with Kafka Cluster ###############"
try:
    topic = client.topics['redirects']
except:
    print "############# Some problem with Kakfa Topic ################"
try:
    balanced_consumer = topic.get_balanced_consumer(
        consumer_group='olaXM',
        auto_commit_enable=True,
        reset_offset_on_start=False,
        use_rdkafka=True,
        zookeeper_connect="kazoo001.olaeu.prv:2181, kazoo002.olaeu.prv:2181,"
                          "kazoo003.olaeu.prv:2181, kazoo004.olaeu.prv:2181,"
                          "kazoo005.olaeu.prv:2181"
    )
except:
    print "######### Some problem with Zookeeper Cluster ##############"
try:
    CLUSTER = Cluster(['cassandra01.olaeu.prv', 'cassandra02.olaeu.prv',
                       'cassandra03.olaeu.prv', 'cassandra04.olaeu.prv'], port=9042)
    SESSION = CLUSTER.connect('ola')
    SESSION.execute('USE olam')
except:
    print "######### Some problem with Cassandra Cluster ##############"
forever = True
while forever:
    message = balanced_consumer.consume()
    if message is not None:
        mdata = message.value
        d = json.loads(mdata)
        cas_id = d['id']
        cas_dt = d['date_added']
        try:
            SESSION.execute(...

**Comment by emmett9001** [comment] 2017-01-13 18:55
@CogumelosMaravilha This is an informational message that can print during connection retries. If your program isn't crashing as a result of that error, it just means that the retry mechanism is working properly.
