### ISSUE TITLE
Fatal Python error: Segmentation fault

### ISSUE THREAD

**Issue by skijash** [Parsely/pykafka#400] opened 2015-12-22 11:03 UTC
Hello,
Has anyone come across segmentation faults while using the lib? I'm suspecting it has something to do with it looking at the thread dumps.
Kafka version is 0.8.2.2, pykafka was 2.0.2, and after an upgrade to 2.1.1 I'm still getting the same error.
Here is what I have:
```
Thread 0x00007f4d2737e700 (most recent call first):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 266 in _feed
  File "/usr/lib/python2.7/threading.py", line 763 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Current thread 0x00007f4d4830c700 (most recent call first):
  File "/home/ubuntu/env/kafka/local/lib/python2.7/site-packages/pykafka/utils/struct_helpers.py", line 96 in _unpack
  File "/home/ubuntu/env/kafka/local/lib/python2.7/site-packages/pykafka/utils/struct_helpers.py", line 49 in unpack_from
  File "/home/ubuntu/env/kafka/local/lib/python2.7/site-packages/pykafka/protocol.py", line 201 in decode
  File "/home/ubuntu/env/kafka/local/lib/python2.7/site-packages/pykafka/protocol.py", line 321 in decode
  File "/home/ubuntu/env/kafka/local/lib/python2.7/site-packages/pykafka/protocol.py", line 738 in _unpack_message_set
  File "/home/ubuntu/env/kafka/local/lib/python2.7/site-packages/pykafka/protocol.py", line 749 in _unpack_message_set
  File "/home/ubuntu/env/kafka/local/lib/python2.7/site-packages/pykafka/protocol.py", line 731 in __init__
  File "/home/ubuntu/env/kafka/local/lib/python2.7/site-packages/pykafka/handlers.py", line 61 in get
  File "/home/ubuntu/env/kafka/local/lib/python2.7/site-packages/pykafka/broker.py", line 244 in fetch_messages
  File "/home/ubuntu/env/kafka/local/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 685 in fetch
  File "/home/ubuntu/env/kafka/local/lib/python2.7/site-packages/pykafka/simpleconsumer.py", line 336 in fetcher
  File "/usr/lib/python2.7/threading.py", line 763 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Thread 0x00007f4d45f04700 (most recent call first):
  File "/usr/lib/python2.7/threading.py", line 358 in wait
  File "/usr/lib/python2.7/Queue.py", line 177 in get
  File "/home/ubuntu/env/kafka/local/lib/python2.7/site-packages/pykafka/handlers.py", line 150 in worker
  File "/usr/lib/python2.7/threading.py", line 763 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Thread 0x00007f4d27fff700 (most recent call first):
  File "/home/ubuntu/env/kafka/local/lib/python2.7/site-packages/kazoo/handlers/threading.py", line 147 in select
  File "/home/ubuntu/env/kafka/local/lib/python2.7/site-packages/kazoo/protocol/connection.py", line 529 in _connect_attempt
  File "/home/ubuntu/env/kafka/local/lib/python2.7/site-packages/kazoo/protocol/connection.py", line 488 in _connect_loop
  File "/home/ubuntu/env/kafka/local/lib/python2.7/site-packages/kazoo/retry.py", line 123 in __call__
  File "/home/ubuntu/env/kafka/local/lib/python2.7/site-packages/kazoo/protocol/connection.py", line 471 in zk_loop
  File "/usr/lib/python2.7/threading.py", line 763 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Thread 0x00007f4d44f02700 (most recent call first):
  File "/usr/lib/python2.7/threading.py", line 339 in wait
  File "/usr/lib/python2.7/Queue.py", line 168 in get
  File "/home/ubuntu/env/kafka/local/lib/python2.7/site-packages/kazoo/handlers/threading.py", line 95 in _thread_worker
  File "/usr/lib/python2.7/threading.py", line 763 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Thread 0x00007f4d45703700 (most recent call first):
  File "/usr/lib/python2.7/threading.py", line 339 in wait
  File "/usr/lib/python2.7/Queue.py", line 168 in get
  File "/home/ubuntu/env/kafka/local/lib/python2.7/site-packages/kazoo/handlers/threading.py", line 95 in _thread_worker
  File "/usr/lib/python2.7/threading.py", line 763 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Thread 0x00007f4d46806700 (most recent call first):
  File "/usr/lib/python2.7/threading.py", line 358 in wait
  File "/usr/lib/python2.7/Queue.py", line 177 in get
  File "/home/ubuntu/env/kafka/local/lib/python2.7/site-packages/pykafka/handlers.py", line 150 in worker
  File "/usr/lib/python2.7/threading.py", line 763 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Thread 0x00007f4d47108700 (most recent call first):
  File "/usr/lib/python2.7/threading.py", line 358 in wait
  File "/usr/lib/python2.7/Queue.py", line 177 in get
  File "/home/ubuntu/env/kafka/local/lib/python2.7/site-packages/pykafka/handlers.py", line 150 in worker
  File "/usr/lib/python2.7/threading.py", line 763 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Thread 0x00007f4d47a0a700 (most recent call first):
  File "/usr/lib/python2.7/threading.py", line 358 in wait
  File "/usr/lib/python2.7/Queue.py", line 177 in get
  File "/home/ubuntu/env/kafka/local/lib/python2.7/site-packages/pykafka/handlers.py", line 150 in worker
  File "/usr/lib/python2.7/threading.py", line 763 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Thread 0x00007f4d4bfd1740 (most recent call first):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 104 in put
  File "/home/ubuntu/cordial-kafka/util/queue.py", line 67 in put
  File "/home/ubuntu/cordial-kafka/kafka/reader.py", line 39 in run
  File "kafka_indexer.py", line 46 in main
  File "kafka_indexer.py", line 66 in <module>
Segmentation fault
```

I'm using a BalancedConsumer, and these segfaults are happening after couple of hours of running. The only suspicious thing I see in kafka logs around the time segfault happened is this:

`INFO Rolled new log segment for '__consumer_offsets-28' in 2 ms. (kafka.log.Log)`

Zookeeper logs do not have anything interesting.
I'm guessing this could have something to do with pykafka lib since current thread dump shows fetching going on.

**Comment by emmett9001** [comment] 2015-12-23 15:57
Thanks @skijash. It looks like the segfault is happening during a call to `struct.unpack_from`, which makes me think there's either some corrupt data in the message set you'r unpacking or there's a buffer leak in pykafka that's gone unnoticed and is allowing data in the buffer to become corrupt over repeated runs. It's also possible that there's an error causing this segfault in our implementation of `utils.compression.decode_snappy`. It's pretty tough to say much about this without more information - is there any more you can provide, like sample messages or demo code? It would be interesting to get a debugger prompt in response to these errors to be able to examine the current state of the buffer.

**Comment by jasonrhaas** [comment] 2015-12-26 17:25
Not sure if this is releated, but I've been catching a lot of these buffer errors lately when trying to consume from kafka using the `simpleconsumer`:

```
error: unpack_from requires a buffer of at least 842019120 bytes
  File "kafkaspout_base.py", line 125, in emit_next
    msg = self.consumer.consume()
  File "pykafka/simpleconsumer.py", line 371, in consume
    self._raise_worker_exceptions()
  File "pykafka/simpleconsumer.py", line 203, in _raise_worker_exceptions
    raise ex
```

**Comment by skijash** [comment] 2015-12-29 08:56
Tried without compression, same thing, same stack trace.
Messages are simple json documents, like this one:
```
ca = {
    "_type": "contactactivities",
    "_source": {
        "ats": "2015-10-08T20:02:04.000Z",
        "a": "message-sent",
        "mcID": "50:5615378d0e6f54033dc2e211:ot:55a0860929aa544d75822e26:1",
        "msID": "50:5615378d0e6f54033dc2e211:ot",
        "cID": "55a0860929aa544d75822e26",
        "ts": "2015-10-08T20:02:04.208Z"
    }
}
```
Only "ts" field value is changing, to exclude the possibility of bad data.
Running with a debugger now.

**Comment by emmett9001** [comment] 2016-01-08 18:15
Thanks @skijash, it's good to know that this isn't related to snappy compression. If you find anything in your debugger runs, please do post it here. I'm not sure how I can reproduce this myself at the moment - I don't see anything like this in Parse.ly's own logfiles.

**Comment by emmett9001** [comment] 2016-02-06 00:07
@jasonrhaas @skijash Do you have any additional information to provide on this issue?

**Comment by skijash** [comment] 2016-02-08 12:14
This project has been paused for the last couple of weeks, sorry for not updating this issue.
By setting up tracking of all sorts of stats, I have found that this is most likely happening due to memory running out. I'll debug some more soon to find out if there is a memory leak somewhere or a gc problem.

**Comment by emmett9001** [comment] 2016-05-13 18:06
Closing this as a duplicate of #470 since it's gone a long time without any actionable information and it seems fairly likely this is related to memory issues.

**Closed by emmett9001** 2016-05-13 18:06 UTC
Labels: backlog, bug, hazy, help wanted, needs response
