### ISSUE TITLE
race condition in RequestHandler?

### ISSUE THREAD

**Issue by blooshirt** [Parsely/pykafka#309] opened 2015-10-20 15:17 UTC
I believe there to be a possible race condition in RequestHandler which could cause lockage during GC of the object. Specificically, if the RequestHandler object is cleaned up before the final task is marked as done [here](https://github.com/Parsely/pykafka/blob/master/pykafka/handlers.py#L154), then the thread will block [here](https://github.com/Parsely/pykafka/blob/master/pykafka/handlers.py#L130). A possible manifestation of this issue is sometimes occurring on creation of a client.
* Broker is created [here](https://github.com/Parsely/pykafka/blob/master/pykafka/cluster.py#L212) and sets up a request shortly thereafter.
* That broker soon goes out of scope, so the only reference 
 to its handler is the weakref in the request thread.
* The race condition occurs when a ReferenceError is thrown before or when the task is marked as done, meaning that the
 join call [here](https://github.com/Parsely/pykafka/blob/2.0.0/pykafka/handlers.py#L130) blocks forever.

The issue is difficult to reproduce, but I've seen it occur a number of times in our testing. I'm not really sure how one would go about fixing it, but if anyone can come up with a suggestion, I would be happy to implement and test.

**Comment by yungchin** [comment] 2015-10-21 09:52
Thanks for reporting this. Just out of curiosity: do you see both the logging messages about the ReferenceError and about entering `stop()` appear in your logs?

I coded up an alternative version of the thread worker while I was working on #258, which didn't have any `weakref` in it, but I decided against it because it changed more code. I'll go find it and rebase it - if you could test if that works better for you that would be great.

**Comment by blooshirt** [comment] 2015-10-21 10:24
> Just out of curiosity: do you see both the logging messages about the ReferenceError and about entering `stop()` appear in your logs?

Yes. Including the logs below with comments. (I added extra logging which showed the bug more explicitly)
````
MainThread:pykafka.cluster 2015-10-20 14:35:39,587 after broker; broker=<pykafka.broker.Broker at 0x7fd0190c15f0 (host=localhost, port=6667, id=-1)>
````
Broker is created [here](https://github.com/Parsely/pykafka/blob/master/pykafka/cluster.py#L212).
````
Thread-1:pykafka.handlers 2015-10-20 14:35:39,589 start worker
MainThread:pykafka.cluster 2015-10-20 14:35:39,595 after broker.request_metadata; response=<pykafka.protocol.MetadataResponse object at 0x7fd0190ce110>
````
Request is made, worker is [started](https://github.com/Parsely/pykafka/blob/master/pykafka/handlers.py#L138), future is responded to and [response received](https://github.com/Parsely/pykafka/blob/master/pykafka/cluster.py#L218).
````
MainThread:pykafka.handlers 2015-10-20 14:35:39,600 __del__; self=<pykafka.handlers.RequestHandler object at 0x7fd0190beb90>
````
Broker goes [out of scope](https://github.com/TAKEALOT/pykafka/blob/master/pykafka/cluster.py#L220), GC begins to [clean up the handler](https://github.com/Parsely/pykafka/blob/master/pykafka/handlers.py#L105).
````
MainThread:pykafka.handlers 2015-10-20 14:35:39,602 before flush; _requests=<Queue.Queue instance at 0x7fd0190c1758>
Thread-1:pykafka.handlers 2015-10-20 14:35:39,601 ReferenceError in handler - dead weakref
Traceback (most recent call last):
  File "/workspace/pykafka/pykafka/handlers.py", line 158, in worker
    self._requests.task_done()
ReferenceError: weakly-referenced object no longer exists
Thread-1:pykafka.handlers 2015-10-20 14:35:39,619 RequestHandler worker: exiting cleanly
````
The `stop()` method tries to join the requests, but just before this can occur, the thread encounters the `ReferenceError`, and cannot mark the task as done, so the `join` blocks indefinitely.

> I'll go find it and rebase it - if you could test if that works better for you that would be great.

Would be happy to.

**Comment by yungchin** [comment] 2015-10-21 13:05
@blooshirt thanks very much for the additional info, it helped me a lot to better understand the issue. I think #310 should address the problem, but like you said, it's not easy to reproduce and in fact I've not been able to come up with a suitable test to add to the test suite.

**Comment by yungchin** [comment] 2015-10-21 13:22
@blooshirt oops #310 still contains some sillyness, will push a fix.

**Comment by yungchin** [comment] 2015-10-21 13:35
@blooshirt fixed that now, sorry for the noise.

**Comment by blooshirt** [comment] 2015-10-21 14:31
@yungchin that seems to have fixed the issue - thanks. I can reliably reproduce the race condition if i add a short sleep before [this](https://github.com/Parsely/pykafka/blob/master/pykafka/handlers.py#L154) line. Doing the same with the code in #310 doesn't cause the issue.

**Comment by blooshirt** [comment] 2015-10-21 14:36
@yungchin as an aside, am I right in saying that this issue could be a possible cause of #260?

**Comment by yungchin** [comment] 2015-10-21 15:27
@blooshirt thanks for testing this right away!!

I believe this race condition was newly introduced with #258, and #260 was around before #258 got merged. The problem with #260 is that so far it has seemed impossible to reproduce :(

**Closed** 2015-10-21 18:37 UTC
Labels: bug, in progress
