### ISSUE TITLE
consumer rate decreasing

### ISSUE THREAD

**Issue by arita37** [Parsely/pykafka#791] opened 2018-04-25 01:23 UTC
Hello,

We are using normal code as follow :
https://github.com/Parsely/pykafka/issues/781

```
consumer = topic.get_balanced_consumer()  # all default parameters...  3 balanced consumer
while True:
    try:
        for message in consumer:
              ii+=1
              msgraw = consumer.consume()
              msg    = msgraw.value.decode('utf8')
              msg    = json.loads(msg)   
              .... #very fast process
              producer.produce(json_data)
   except Exception as e : 
               print(e)
```

What happens :   
   0 min - 5 mins :   Input flow is  same Kafka server (test server with fixed flow).
   After  5 mins:      Almost half of the expected.

1) Just wondering if you have done some tests to see the consuming flow is matching kafka output ?

2)  Is 1/2 of the flow matching anything in consumer config ?

Can we re-open this issue ?

**Comment by emmett9001** [comment] 2018-04-25 16:27
Duplicate of https://github.com/Parsely/pykafka/issues/790

**Closed** 2018-04-25 16:27 UTC
