### ISSUE TITLE
ReferenceError: weakly-referenced object no longer exists

### ISSUE THREAD

**Issue by Emor93** [Parsely/pykafka#422] opened 2016-01-20 07:33 UTC
Hi all,
when I use pykafka producer to send some messages to kafka in idle,it always success. But when i put the code in a py file,and execute it,it failed.
Here are detailed information:
Idle:
```
[root@dap194 home]# python
Python 2.7.10 (default, Jan 20 2016, 14:08:19) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
 from pykafka import KafkaClient
client = KafkaClient(hosts="10.43.159.115:9092")
 topic = client.topics['mytopic']
 print topic
pykafka.topic.Topic at 0x7ff0b8532d50 (name=mytopic)
 producer = topic.get_producer()
 producer.produce('test message ')
```
This one is ok,the kafka had received te message. 

py file:
```
[root@dap194 home]# python test.py 
DEBUG:pykafka.connection:Connecting to 10.43.159.115:9092
DEBUG:pykafka.connection:Successfully connected to 10.43.159.115:9092
INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
INFO:pykafka.cluster:Discovered 1 brokers
DEBUG:pykafka.cluster:Discovered broker id 159115: centos115:9092
DEBUG:pykafka.connection:Connecting to centos115:9092
DEBUG:pykafka.connection:Successfully connected to centos115:9092
INFO:pykafka.cluster:Discovered 3 topics
DEBUG:pykafka.cluster:Discovered topic 'mytopic'
DEBUG:pykafka.cluster:Discovered topic 'mytest'
DEBUG:pykafka.cluster:Discovered topic 'true_cloud_datapoint_topic'
DEBUG:pykafka.connection:Connecting to 10.43.159.115:9092
DEBUG:pykafka.connection:Successfully connected to 10.43.159.115:9092
INFO:pykafka.handlers:RequestHandler.stop: about to flush requests queue
INFO:pykafka.topic:Adding 1 partitions
DEBUG:pykafka.topic:Adding partition mytopic/0
<pykafka.topic.Topic at 0x7fbeeeceaed0 (name=mytopic)>
INFO:pykafka.producer:Starting new produce worker for broker 159115
DEBUG:pykafka.producer:Finalising <pykafka.producer.Producer at 0x7fbeeecfe610>
INFO:pykafka.producer:Blocking until all messages are sent
INFO:pykafka.handlers:RequestHandler worker: exiting cleanly
INFO:pykafka.handlers:RequestHandler worker: exiting cleanly
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/python27/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/python27/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/python27/lib/python2.7/site-packages/pykafka-2.1.2-py2.7.egg/pykafka/producer.py", line 441, in queue_reader
    self.producer._worker_exception = sys.exc_info()
ReferenceError: weakly-referenced object no longer exists
```

It's weird that the same code,it could be executed successfully in idle,but failed when i execute it by python xxx.py.

Btw,the code in test.py is:
```python
#!/usr/bin/python
from pykafka import KafkaClient
import logging as log
log.basicConfig(level=log.DEBUG)
client = KafkaClient(hosts="10.43.159.115:9092")
topic = client.topics['mytopic']
print topic
producer = topic.get_producer()
producer.produce('test message ')
```

Pykafka Version is 2.1.2

Thank you!

**Comment by yungchin** [comment] 2016-01-20 14:16
Thanks very much for reporting this. Your finding confirms #352 - which said I had a hunch that this kind of error would be possible. The reason it works fine in the interpreter is that there you keep the producer instance alive, whereas in the scripted run the producer may have been finalised before the worker thread gets to empty the queue.

I'll rename #352 and it will jump up the priority list now. Do feel free to add suggestions and any further information that may come to mind to #352.

**Comment by yungchin** [comment] 2016-01-20 14:24
@Emor93 for the very short term, if you need a work-around, the `atexit`-based technique [mentioned here][0] should effectively deal with the problem.

[0]: https://github.com/Parsely/pykafka/issues/352#issuecomment-156488199

**Comment by BlackRider97** [comment] 2016-06-07 12:43
```
Traceback (most recent call last):
  File "/app/venv/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/app/venv/local/lib/python2.7/site-packages/pykafka/producer.py", line 534, in queue_reader
    self.producer._worker_exception = sys.exc_info()
ReferenceError: weakly-referenced object no longer exists
<Greenlet at 0x7eff384d62d0: queue_reader> failed with ReferenceError
```

```
pykafka==2.4.0
gevent==1.0.1
```
I am getting this exception while producing data to kafka.

**Comment by emmett9001** [comment] 2016-06-07 12:50
@BlackRider97 Thanks for the traceback. Please post the code you're using to produce with PyKafka - this is often caused by not retaining a reference to the `Producer` object.

**Comment by messense** [comment] 2016-06-20 01:43
I have the same problem in production.

```
2016-06-19 15:01:56,521 INFO MainThread pykafka.producer._wait_all:479   Blocking until all messages are sent
Exception in thread 6: pykafka.OwnedBroker.queue_reader for broker 3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/brm_index/venv/local/lib/python2.7/site-packages/pykafka/producer.py", line 534, in queue_reader
    self.producer._worker_exception = sys.exc_info()
ReferenceError: weakly-referenced object no longer exists

Exception in thread 7: pykafka.OwnedBroker.queue_reader for broker 2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/brm_index/venv/local/lib/python2.7/site-packages/pykafka/producer.py", line 534, in queue_reader
    self.producer._worker_exception = sys.exc_info()
ReferenceError: weakly-referenced object no longer exists

Exception in thread 5: pykafka.OwnedBroker.queue_reader for broker 1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/brm_index/venv/local/lib/python2.7/site-packages/pykafka/producer.py", line 534, in queue_reader
    self.producer._worker_exception = sys.exc_info()
ReferenceError: weakly-referenced object no longer exists
```

My code is something like:

```python
from pykafka import KafkaClient


class Scheduler(object):

    def __init__(self):
        self.kafka = KafkaClient('kafka hosts', 'zookeeper hosts')
        topic = self.kafka.topics['test']
        self.producer = topic.get_producer(max_retries=5)

    def run(self):
        # messages from some database
        messages = []
        for msg in messages:
            self.producer.produce(msg.encode('utf-8'))


if __name__ == '__main__':
    scheduler = Scheduler()
    scheduler.run()
```

**Comment by sunqb** [comment] 2016-07-04 12:18
hi,can you solve this problem @emmett9001

**Comment by brianbruggeman** [comment] 2016-07-05 18:48
This is a blocker for us.

I also have a very similar problem to @messense.  My code is more or less identical to his.  I wrap pykafka with my own class and hold on to references to the producer and topic.  The first time I send a piece of data, the producer/topic appears to be fine.  The second time, I have a ReferenceError: weakly-referenced object no longer exists.  

What's more concerning is that I do not seem to see this problem if I step through the code -- only if I run.  That tells me there's likely a problem with the threading conditions.

**Comment by emmett9001** [comment] 2016-07-05 19:14
These tracebacks actually look like they might be a red herring. Notice the `pykafka.producer._wait_all:479   Blocking until all messages are sent` preceding all weakref errors [here](https://github.com/Parsely/pykafka/issues/422#issuecomment-227034618). `_wait_all` is called when `stop()` is hit, which is called in response to another error. Can anyone on this thread give any additional information about that the error might be that's causing `stop()` to be called?

**Comment by brianbruggeman** [comment] 2016-07-05 19:15
Here's another traceback, for what it's worth:

```
Exception in thread 9: pykafka.OwnedBroker.queue_reader for broker 0:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/pykafka/producer.py", line 534, in queue_reader
    self.producer._worker_exception = sys.exc_info()
ReferenceError: weakly-referenced object no longer exists
```

**Comment by sunqb** [comment] 2016-07-06 15:58
@brianbruggeman i have the same error

**Comment by emmett9001** [comment] 2016-07-06 18:35
@messense At what point in your program is the exception raised? Does it happen after the program has exited, or during execution?

**Comment by messense** [comment] 2016-07-07 01:24
@emmett9001 During execution.

**Comment by sunqb** [comment] 2016-07-07 08:32
my pykafka version is 2.4.0 ,and what about yours?

**Comment by emmett9001** [comment] 2016-07-07 16:56
As in #352, we've seen this issue in the past when the `Producer` instance gets finalized before the worker thread has had a chance to flush its queue. Is there any situation in any of the code samples given here in which the `Producer` instance could be finalized before all messages have been sent?

**Comment by messense** [comment] 2016-07-08 01:39
@emmett9001 Use the ``atexit`` technique works for me. Some logs:

```
2016-07-08 09:33:17,355 INFO MainThread pykafka.topic.<module>:40    Successfully loaded pykafka.rdkafka extension.
2016-07-08 09:33:17,536 INFO MainThread raven.base.Client.__init__:188   Raven is not configured (logging is disabled). Please see the documentation for more information.
2016-07-08 09:33:17,711 INFO Thread-3 kazoo.client._connect:575   Connecting to localhost:2181
2016-07-08 09:33:17,720 INFO Thread-3 kazoo.client._session_callback:444   Zookeeper connection established, state: CONNECTED
2016-07-08 09:33:17,735 INFO Thread-3 kazoo.client._connect_attempt:542   Closing connection to localhost:2181
2016-07-08 09:33:17,735 INFO Thread-3 kazoo.client._session_callback:448   Zookeeper session lost, state: CLOSED
2016-07-08 09:33:17,743 INFO MainThread pykafka.handlers.stop:176   RequestHandler.stop: about to flush requests queue
2016-07-08 09:33:17,743 INFO MainThread pykafka.cluster._update_brokers:338   Discovered 1 brokers
2016-07-08 09:33:17,745 INFO MainThread pykafka.cluster._update_topics:128   Discovered 25 topics
2016-07-08 09:33:17,746 INFO Thread-6 kazoo.client._connect:575   Connecting to localhost:2181
2016-07-08 09:33:17,748 INFO Thread-6 kazoo.client._session_callback:444   Zookeeper connection established, state: CONNECTED
2016-07-08 09:33:17,751 INFO Thread-6 kazoo.client._connect_attempt:542   Closing connection to localhost:2181
2016-07-08 09:33:17,751 INFO Thread-6 kazoo.client._session_callback:448   Zookeeper session lost, state: CLOSED
2016-07-08 09:33:17,755 INFO MainThread pykafka.handlers.stop:176   RequestHandler.stop: about to flush requests queue
2016-07-08 09:33:17,755 INFO MainThread pykafka.topic.update:160   Adding 5 partitions
2016-07-08 09:33:17,756 INFO MainThread pykafka.producer.start:538   Starting new produce worker for broker 0
2016-07-08 09:33:17,756 INFO MainThread urllib3.connectionpool._new_conn:214   Starting new HTTP connection (1): ovh-0300.bosondata.net
2016-07-08 09:33:18,662 INFO MainThread elasticsearch.log_request_success:63    GET http://localhost:9000/abnormal/abnormal/_search?search_type=scan&scroll=10m [status:200 request:0.906s]
No handlers could be found for logger "elasticsearch.trace"
2016-07-08 09:33:18,743 INFO 0: pykafka.RequestHandler.worker for 172.16.42.1:9092 pykafka.handlers.worker:206   RequestHandler worker: exiting cleanly
2016-07-08 09:33:18,757 INFO 2: pykafka.RequestHandler.worker for 172.16.42.1:9092 pykafka.handlers.worker:206   RequestHandler worker: exiting cleanly
2016-07-08 09:33:18,998 INFO MainThread elasticsearch.log_request_success:63    GET http://localhost:9000/_search/scroll?scroll=10m [status:200 request:0.334s]
2016-07-08 09:33:19,345 INFO MainThread elasticsearch.log_request_success:63    GET http://localhost:9000/_search/scroll?scroll=10m [status:200 request:0.339s]
2016-07-08 09:33:21,406 INFO Dummy-7 pykafka.producer._wait_all:479   Blocking until all messages are sent
2016-07-08 09:33:27,794 INFO 3: pykafka.OwnedBroker.queue_reader for broker 0 pykafka.producer.queue_reader:537   Worker exited for broker 172.16.42.1:9092
2016-07-08 09:33:27,795 INFO Dummy-7 pykafka.producer._wait_all:479   Blocking until all messages are sent
2016-07-08 09:33:27,795 INFO Dummy-7 pykafka.handlers.stop:176   RequestHandler.stop: about to flush requests queue
2016-07-08 09:33:27,806 INFO 1: pykafka.RequestHandler.worker for 172.16.42.1:9092 pykafka.handlers.worker:206   RequestHandler worker: exiting cleanly
```

**Comment by emmett9001** [comment] 2016-07-08 16:36
In general if the `atexit` fix works, I'd still prefer to `wontfix` this.

**Comment by brianbruggeman** [comment] 2016-07-09 02:46
@emmett9001 I added the `atexit` and I can confirm that this prevented my errors from popping up.  However, I now have processes hanging on exit.  Note that this is workable only because I intend the processes to run 'forever'.  But, I think there's still a bug.

**Comment by emmett9001** [comment] 2016-07-21 03:41
@brianbruggeman If you can reliably replicate the case where the producer hands on exit, please open a fresh issue. Thanks for your contributions!

**Closed by emmett9001** 2016-07-21 03:41 UTC
Labels: bug, hazy

**Comment by itgeniusshuai** [comment] 2016-10-12 12:24
hi,could one tell me how to reslove this problem

**Comment by emmett9001** [comment] 2016-10-12 15:42
@itgeniusshuai [This](https://github.com/Parsely/pykafka/issues/352#issuecomment-156488199) is the pattern we've been directing people to
