### ISSUE TITLE
pykafka.ownedBroker.queue_reader in pyspark

### ISSUE THREAD

**Issue by christianbo** [Parsely/pykafka#571] opened 2016-06-17 02:10 UTC
when using producer of pykafka in pyspark, i get a problem:
```
Exception in thread 5 : pykafka.ownedBroker.queue_reader for broker 55:
Traceback(most recent call last):
File"/usr/locla/lib/python2.7/threading.py". line 810, in __bootstrap innerself.run()
File"/usr/locla/lib/python2.7/threading.py".line 763 in runself.__target(*self.__args,**self.__kwargs)
File "/usr/local/lib/python2.7/site-packages/pykafka/producer.py".line 529, in queue_reader 
self.producer._worker_exception:sys.exc_info()
Reference Error: weakly-referenced object no longer exists
```

I create producer in each mapPartitions, there are 4 partitions,so  I got 4 printings as above，and the program pending, not exist,please help 

**PyKafka version**: 2.4
**Kafka version**:

**Comment by emmett9001** [comment] 2016-06-17 12:03
Hi @christianbo, thanks for filing this. Could you please include an example of the code you're using to set up and use your `Producer`? My guess is that you're attempting to produce without keeping a reference to the `Topic`.

**Comment by christianbo** [comment] 2016-06-18 09:14
my code is like this
def sentkafka(messages):
    kafka = KafkaClient(hosts="xxx")
    producer = kafka.topics['test'].get_producer()
    for m in messages:
        yield producer.produce(m)

sentRDD = text.mapPartitions(sentkafka)

text is a RDD
then i call sentRDD.count() 

i do try the 
kafka = KafkaClient(hosts="xxx")
producer = kafka.topics['test'].get_producer()
producer.produce('test message')
can sent single message

**Comment by emmett9001** [comment] 2016-06-21 14:00
Duplicate of #422

**Closed by emmett9001** 2016-06-21 14:00 UTC
Labels: hazy, question
