### ISSUE TITLE
Race condition when creating multi BalancedConsumer

### ISSUE THREAD

**Issue by xqliang** [Parsely/pykafka#313] opened 2015-10-24 08:24 UTC
```python
    def _add_self(self):
        """Register this consumer in zookeeper.
        This method ensures that the number of participants is at most the
        number of partitions.
        """
        participants = self._get_participants()
        # NOTE: Race condition here
        if len(self._topic.partitions) <= len(participants):
            raise KafkaException("Cannot add consumer: more consumers than partitions")

        self._zookeeper.create(
            self._path_self, self._topic.name, ephemeral=True, makepath=True)
```
As shown above, [there is](https://github.com/Parsely/pykafka/blob/master/pykafka/balancedconsumer.py#L412) a race condition when multi processes create BalancedConsumer at the same time with the same `consumer_group`.

When a race condition occurred, the consumer instance holds [empty partition](https://github.com/Parsely/pykafka/blob/master/pykafka/balancedconsumer.py#L450), and the internal `_consumer ` is [not inited](https://github.com/Parsely/pykafka/blob/master/pykafka/balancedconsumer.py#L464).

Moreover, because of the [null](https://github.com/Parsely/pykafka/blob/master/pykafka/balancedconsumer.py#L250) `_consumer`, there seems to be no way to stop it.

May be we can stop the consumer and raise an exception when [calling _decide_partitions](https://github.com/Parsely/pykafka/blob/master/pykafka/balancedconsumer.py#L450) returns empty partition?

**Comment by yungchin** [comment] 2015-10-26 16:26
Thanks for reporting this! Just to make sure I fully understand the issue: the fact that `_add_self` may raise an exception is expected behaviour for your use case, but the problem is that such an instance cannot be properly cleaned up afterwards, is that right?

Would changing `BalancedConsumer.stop()` so that it has
```python
if self._consumer is not None:
    self._consumer.stop()
```
be a sufficient solution in that case? (That's probably a useful change anyway.)

**Comment by emmett9001** [comment] 2015-10-26 22:49
From the comments so far, I gather that the issue is essentially that there exists a situation in which the `BalancedConsumer` can assign itself no partitions (in particular, this race condition), which causes a bunch of other problems. Assuming that's an accurate assessment, what can we do to ensure that this never happens? I think we should avoid adding more locks to the mix if possible. Maybe we can check [here](https://github.com/Parsely/pykafka/blob/10ca834a2dadc47de07cf7cb8288672d9f973851/pykafka/balancedconsumer.py#L450) whether `new_partitions` is empty and simply call `stop()` if so.

**Closed** 2015-10-27 18:30 UTC
Labels: bug
