### ISSUE TITLE
forget to disconect socket ?

### ISSUE THREAD

**Issue by GhostZCH** [Parsely/pykafka#257] opened 2015-09-07 08:24 UTC
recently, I met a problem about kafka connections, the phenomenon is that the TCP connections number on Kafka server was more than 20,000, and I reviewed my Producer and Consumer code, also the pyKafka code, I found a potential connection leak problem. 

Here's my test code and result:

1. build one  KafkaClient with two connections

        if __name__ == '__main__':
               client = KafkaClient(hosts)
                raw_input()

        ➜  ~  netstat | grep 9092
        tcp        0      0 10.8.192.*:51778       10.8.255.*:9092       ESTABLISHED
        tcp        0      0 10.8.192.*:51777       10.8.255.*:9092       ESTABLISHED

2. build three  KafkaClient with six connections

        if __name__ == '__main__':
            for i in xrange(3):
                client = KafkaClient(hosts)
            raw_input()

        ➜  ~  netstat | grep 9092
        tcp        0      0 10.8.192.*:58035       **********************:9092 ESTABLISHED
        tcp        0      0 10.8.192.*:58037       **********************:9092 ESTABLISHED
        tcp        0      0 10.8.192.*:58039       **********************:9092 ESTABLISHED
        tcp        0      0 10.8.192.*:58036       **********************:9092 ESTABLISHED
        tcp        0      0 10.8.192.*:58034       **********************:9092 ESTABLISHED
        tcp        0      0 10.8.192.*:58038       **********************:9092 ESTABLISHED
 
forgot disconnect after _get_metadata(where I write TODO)  ?

    def _get_metadata(self):
            """Get fresh cluster metadata from a broker."""
            # Works either on existing brokers or seed_hosts list
            brokers = [b for b in self.brokers.values() if b.connected]
            if brokers:
                for broker in brokers:
                    response = broker.request_metadata()
                    if response is not None:
                        return response
            else:  # try seed hosts
                brokers = self._seed_hosts.split(',')
                for broker_str in brokers:
                    try:
                        h, p = broker_str.split(':')
                        broker = Broker(-1, h, p, self._handler,
                                        self._socket_timeout_ms,
                                        self._offsets_channel_socket_timeout_ms,
                                        buffer_size=1024 * 1024)
                        response = broker.request_metadata()
                        # TODO: **broker.disconnect** ?
                        if response is not None:
                            return response

                    except:
                        log.exception('Unable to connect to broker %s',
                                      broker_str)
            # Couldn't connect anywhere. Raise an error.
            raise Exception('Unable to connect to a broker to fetch metadata.')

sorry about my English and how can we release client correctly.

**Comment by yungchin** [comment] 2015-09-07 14:17
Thanks for reporting this.

I can confirm that the number of connections keeps growing with every instantiation of a `KafkaClient`. In addition, `threading.active_count()` grows too, and I strongly suspect that this is related to the discussion in #256 - given that the broker init calls `Broker.connect`, and the consumer init triggers `Broker.connect_offsets_channel` and those two methods are very similar internally.

**Comment by yungchin** [comment] 2015-09-07 20:13
@GhostZCH I'd be grateful if you could check out #258

**Comment by GhostZCH** [comment] 2015-09-08 03:59
@yungchin seems not work. It looks like cluster not released when client released and connecting not close when broker released.

**Comment by yungchin** [comment] 2015-09-08 06:41
Ouch - you're right, thanks. I'd been borrowing @emmett9001's test script from #255, after jumping to conclusions that these two things are related - but it turns out #258 so far only resolves the multiple `SimpleConsumer` scenario, but not the multiple `KafkaClient` one. There may be some more finalisers not running elsewhere. Will do some more digging!

**Comment by GhostZCH** [comment] 2015-09-08 08:54
@yungchin 
cluster: self._topics[name] = Topic(self, meta)
topic: self._cluster = cluster
should :
self._cluster = weakref.proxy(cluster)

cluster could release, but RequestHandler still not release

**Comment by yungchin** [comment] 2015-09-08 09:10
@GhostZCH thanks, I was just playing with the exact same line :)
It works somewhat, if I also pass a shorter `socket_timeout_ms` into `KafkaClient`, but there seem to be some lockups when you do that and then instantiate multiple instances of `KafkaClient`. Still trying to get what that's about.

Also: I wouldn't particularly like this solution, because it would mean that if a user didn't keep a handle to the client directly, it would die:
```
prod = pykafka.KafkaClient("localhost:9092", socket_timeout_ms=1000).topics["hello"].get_producer()
[...]
ReferenceError: weakly-referenced object no longer exists
```

**Comment by GhostZCH** [comment] 2015-09-08 09:51
@yungchin Oh, I just want to show the reason why cluster not realse. 

Also I find 'atexit.register(self.stop)' will case `RequestHandler` not released by gc util the program shut down. I try remove that line, handler will released, but may not a good solution.

Thank you for your attention

**Comment by yungchin** [comment] 2015-09-08 10:30
Thanks @GhostZCH - I do agree that's the reason. I think eventually the solution may have to be the other way around, so that `Cluster` will no longer hold strong refs to `Topic` (my first idea would be that `TopicDict` would only hold topic names as keys, and would hand out but not hold on to real `Topic` instances).

As for `atexit`, that should be dealt with by #258.

The weird thing is, if I apply a `self._cluster = weakref.proxy(cluster)` patch on top of #258, I still have issues: when I do a `del client` I find that `client.cluster` really gets finalised, but typically one `Broker` instance is left behind (I run with a three-broker test cluster, and see only two finalisers run). So that's what still keeps that `RequestHandler` alive even after removing `atexit`.

**Comment by GhostZCH** [comment] 2015-09-08 10:40
def main():
    for i in xrange(10):
        client = KafkaClient(hosts)
        time.sleep(1)

if __name__ == '__main__':
    main()
    gc.collect()
    raw_input('>>>')

**Comment by yungchin** [comment] 2015-09-08 11:11
Ah thanks very much, that was really helpful! I hadn't thought of enlisting the `gc` module. Plugging in `gc.set_debug(gc.DEBUG_LEAK)` before `gc.collect()` revealed the problem.

It turns out there's another reference cycle: between `Topic` and `Partition`. And given that `Partition` also holds references to `Broker` (via `_isr`, `_leader`, and `_replicas`), that's what kept that `Broker` alive.

**Comment by yungchin** [comment] 2015-09-08 11:50
Ok, so to summarise, the issue here is that currently, a gc'd `KafkaClient` leaves its cluster, brokers, _and_ connections behind. There are three separate issues underlying this issue:

 1. the use of `atexit` in `RequestHandler`, which prevented these ever getting gc'd - this is addressed by #258 which should be ready for review
 2. a reference cycle between `Topic` and `Partition` - this one, I would think, is trivially resolved by sticking `self._topic = weakref.proxy(topic)` in `Partition.__init__`. This is ok because there isn't a clear use case where somebody wants to hold a `Partition` directly while discarding the `Topic`
 3. a reference cycle between `Cluster` and `Topic`. This one is more tricky, because people may expect to be able to hold on to the `Topic` only. A rough proposal for keeping that working is outlined above: `Cluster` should instantiate `Topic` instances on-the-fly when requested, rather than holding a dict of them

I can confirm that applying #258 and breaking both reference cycles is sufficient to stop leaking objects for the scenario where we only instantiate and then immediately del a `KafkaClient`. 

@kbourgoin does this sound like a worthwhile way forward?

**Comment by emmett9001** [comment] 2015-09-08 18:33
With respect to 2: I'm not sure we can safely assume that there are no cases where someone wants to hold references to one or more `Partition` instances without having the `Topic` as well.

**Comment by yungchin** [comment] 2015-09-08 23:23
@emmett9001 thanks, ok, in that case we need a more elaborate solution. I suspect the same thing as with 3) should be doable: instantiate a `Partition` on-the-fly from `Topic.partitions.__getitem__`. Although, that would make iterating over them a costly mess....

(So, I was actually going by the hunch that because both `Producer` and `SimpleConsumer` require a `Topic` to be inited with, you'd always need the `Topic` anyway?)

**Comment by yungchin** [comment] 2015-09-10 23:05
Issues 1) (=> #258) and 3) (=> #262) have been dealt with now. I've been delaying on 2) - hoping we might still conclude that that's ok with a simple weakref.... (I'm just going to offer up an appeal to ignorance here: I cannot think of any use case where one would want to hold references to `Partition` only :))

**Comment by yungchin** [comment] 2015-09-10 23:57
@GhostZCH @emmett9001 just as a quick way to demonstrate that 1+2+3 together close this leak, I've pushed a branch https://github.com/Parsely/pykafka/tree/fix/joint-fixes-for-257 which combines #258 and #262 plus a simple weakref-patch to address issue 2). So with that, you should be able to create a new `KafkaClient`, `del` it, and see no thread leaks or lingering connections.

(Note however that as per #255, as soon as you do more than instantiate and then del a `KafkaClient`, a bunch of other refcycles in `SimpleConsumer` and `Producer` come into play.)

**Comment by emmett9001** [comment] 2015-09-19 17:11
Merged #258 - I'm going to keep making my way through these.

**Comment by emmett9001** [comment] 2015-09-24 19:18
Merged #262. Nice work @yungchin, and thanks for going so deep!

**Comment by emmett9001** [comment] 2015-09-24 21:27
Parts 1, 2, and 3 are all in master now.

**Closed** 2015-09-24 21:38 UTC
Labels: bug, reproduced

**Comment by emmett9001** [comment] 2015-09-25 18:12
@GhostZCH Are you creating thousands of `KafkaClient`s? If so, why? A `KafkaClient` is meant to be used to connect to a Kafka cluster and can be used to interact with any number of topics on that cluster. Are you connecting to many different clusters?

**Comment by GhostZCH** [comment] 2015-09-28 09:07
@emmett9001 when sent message to kafka failed, we try to create a new one. after running for days, thousands sockets were created
